### ISSUE TITLE
Improve flexibility of Table component

### ISSUE THREAD

**Issue by emilhe** [snehilvj/dash-mantine-components#10]
In React, the Mantine Table component is populated using html elements. In the current Dash Mantine Components (dmc) wrapper, the elements are constructed from (columns, rows) props as simple text elements. While this choice simplifies the syntax form a Dash perspective, it also reduces flexibility. 

In my first project using dmc, for example, I needed table entries to act as links. I can think of two ways to implement it,

1) Pass html components directly to the table via the children prop
* (+) High flexibilty, as the user can pass any Dash component to the table
* (+) Since Dash components are passed, callbacks can be attached
* (-) The Dash code will be longer (which could be, at least partially, mitigated by providing utility functions)
* (-) Possible, performance might become an issue for large table due to the large number of Dash nodes

2) Pass data in some simply structure, e.g. the current (columns, rows) props, but enable custom rendering  
* (+) High flexibility, as the user can render custom javascript in the table
* (+) Short syntax (at least for simple tables, i.e. as now)
* (-) As the rendered object are not passed from Dash, attaching callbacks is not possible
* (-) Requires the user to write JavaScript, and deal with JavaScript assets
* (-) Requires more implementation effect as compared to (1)

I guess both approaches could be implemented in one component. Alternatively, two table component could be created. Say, a `Table` (or `HtmlTable`?) component that takes html elements as children similar to the Mantine Table component, and a `SimpleTable` (or `Table`?) that renders the children based on (columns, rows) props. What do you think, @snehilvj ?

**Comment by snehilvj** [comment]
Table component now accepts other components as children rather than data directly.
