### ISSUE TITLE
Unable to add an image/icon to Select options

### ISSUE THREAD

**Issue by juanjomendezhealios** [snehilvj/dash-mantine-components#100]
Hi! I'm new to mantine components for Dash in Python, and I'm trying to use the Select component to show different options with an icon in the left, as I previously did with the component Dropdown of dash components.

![Screenshot 2022-10-20 at 08 51 36](https://user-images.githubusercontent.com/105805092/196876791-a8af76a9-6565-4a95-bcdd-993406e115e4.png)

I have decided to use the Select component of dash-mantine in order to separate the select options by categories, the only problem is that, when I try to set the option's label to an Image component, it returns an error.

This is the code I've created. As it is shown, the label instead of only being a string, is a Div component that includes the image I want to show side by side the value of the option.

```
                     dmc.Select(
                        label="Select framework",
                        placeholder="Select one",
                        id="framework-select",
                        value="ng",
                        data=[
                            {
                                "value": "react",
                                "label": html.Div(
                                    [
                                        html.Img(
                                            src="assets/tasks-list/Penguin.png",
                                            height=20,
                                        ),
                                    ]
                                ),
                            },
                            {
                                "value": "svelte",
                                "label": html.Div(
                                    [
                                        html.Img(
                                            src="assets/tasks-list/Penguin.png",
                                            height=20,
                                        ),
                                    ]
                                ),
                            },
                        ],
                        style={"width": 200, "marginBottom": 10},
                    ),
                    dmc.Text(id="selected-value"),
``` 

This is how the Select component looks:

![Screenshot 2022-10-20 at 08 53 40](https://user-images.githubusercontent.com/105805092/196877270-d8bbc8e7-92f0-4ea1-ae56-d32d9441e259.png)

Although, when I click on the Select component an error is thrown in the inspector console. This is the error:

![Screenshot 2022-10-20 at 08 53 48](https://user-images.githubusercontent.com/105805092/196877865-862cb9e7-233b-4714-be31-051f63f2aaa9.png)

My question here is: is it possible to have an image side by side with the text value on the select component options?

Thanks in advance for any response 😉

**Comment by snehilvj** [comment]
This won't be part of the main dmc library. I think a better place for them is a separate library, maybe called dmc-extra-components, though I won't be working on it - open to the community.
