### ISSUE TITLE
Allow for Submittable Form

### ISSUE THREAD

**Issue by BSd3v** [snehilvj/dash-mantine-components#103]
Hello,

I’d like to make a submittable form. 

In order to do so, the inputs will need to be able to have the name attribute optional. Up to you if defaults to id. 

The button will need to be able to have the type attribute optional with default type as button.

**Comment by snehilvj** [comment]
button types have been added in 0.11.0a0 release. Also added `name` prop, which will be available in the next release.

**Comment by BSd3v** [comment]
Just confirming, this is for all inputs, not just TextInput? (PasswordInput,etc)

**Comment by snehilvj** [comment]
Yes of course.
