### ISSUE TITLE
import error - No module name Textarea

### ISSUE THREAD

**Issue by Elbarto** [snehilvj/dash-mantine-components#104]
Hi,

I just installed the dash_mantine_components 0.10.2 on a raspberry pi, and when trying to import it I get the following error :
```
File "/usr/local/lib/python3.7/site-packages/dash_mantine_components/_imports_.py", line 72, in <module>
    from .Textarea import Textarea
ModuleNotFoundError: No module named 'dash_mantine_components.Textarea'
```
I don't have the issue on windows so maybe it's linux specific ?
I've checked in the site-package what is wrong and indeed the module is named  TextArea and not Textarea, so Linux is case sensitive and windows isn't for package import ? (I do have the same version 0.10.2 on my windows and raspberry)

For now i've fix the issue by renaming the module.

**Comment by snehilvj** [comment]
Thanks @Elbarto for reporting the issue. This is not a problem in the latest 0.11.0a0 release, so should also not be present in 0.11.0 release. You can give the alpha version a try but I don't suggest using it in prod just yet.
https://github.com/snehilvj/dash-mantine-components/releases/tag/0.11.0a0
