### ISSUE TITLE
RangeSlider: unable to move handles

### ISSUE THREAD

**Issue by mcpcpc** [snehilvj/dash-mantine-components#105]
## Issue Problem Statement

Unable to move range slider handles if minRange prop is not defined. This issue seems like to be intermittent, depending on the value of your min and max props.

![image](https://user-images.githubusercontent.com/37268479/199479573-76f125f5-8e9f-4bac-bbb0-c4dfaa8758a2.gif)

### Requirements

```
dash-mantine-components==0.11.0a0
```

### Minimal Working Solution

```python
import dash_mantine_components as dmc
from dash import callback, html, Output, Input, Dash

app = Dash(__name__)
app.layout = html.Div(
    [
        dmc.Text(children="Lorem Ipsum", id="range-slider-output"),
        dmc.RangeSlider(
            id={"type": "form", "index": "coil-type"},
            min=1,
            max=50,
            step=1
        )
    ]
)
    
if __name__ == "__main__":
    app.run_server(debug=True)
```

**Comment by snehilvj** [comment]
Hi @mcpcpc, I think what's happening here is that the default value of `minRange` prop is 10, so when you set the `max` to be 6, you need to change the `minRange` prop as well, for example, you can set it to 3.

In the MWS code you have shared, the `max` is set to 50, more than the default `minRange`, so should not see the above issue.

There is another issue with RangeSlider which is observed when you set `min` prop to a negative value. Its a bug in Mantine itself and can be tracked here: https://github.com/mantinedev/mantine/issues/2897.

**Comment by snehilvj** [comment]
Issue has been resolved upstream and dmc master has been updated.
