### ISSUE TITLE
Add mantine Stepper component

### ISSUE THREAD

**Issue by joshgoldenbergno10** [snehilvj/dash-mantine-components#109]
https://mantine.dev/core/stepper/

As discussed on discord - we want the ability to have a high level of timeline of the things that need to happen and then when you click on each step you see eg visualisations or information about the decisions. We currently use tabs quite a lot for things adjacent to this but the problem with them is it's pretty hard to give extra descriptive information on them which is viewable across all tabs without making it look quite ugly (eg putting content above it and fiddling a lot with text and sizes.

**Comment by snehilvj** [comment]
Stepper component has been added, will be available in the next release.

**Comment by joshgoldenbergno10** [comment]
thank you!!!
