### ISSUE TITLE
Select component with searchable as True, we are getting autocomplete popover. can we block it

### ISSUE THREAD

**Issue by ankris-kri** [snehilvj/dash-mantine-components#111]
With searchable set to True in select/multiSelect, we are getting autocomplete popover for the dropdown. Can we set autoComplete = "none" for that <input>

**Comment by nielsdewitte420** [comment]
I'm facing a similar issue as @ankris-kri  reported. Below a quick example:

![image](https://user-images.githubusercontent.com/20623847/202723835-f0cdd487-2d2a-4571-a0d8-f77dd507ead6.png)

In this example you select a 'Project', however if you have chosen one of these options in the past, you get an autocomplete which is undesired. I'm using Google Chrome.

**Comment by snehilvj** [comment]
Fixed. Will be available in the next release.
