### ISSUE TITLE
Allow for Parameter Persistence

### ISSUE THREAD

**Issue by BSd3v** [snehilvj/dash-mantine-components#112]
Hello,

Please add the parameter persistence for inputs, this is necessary when using these elements repeatedly. 👍

**Comment by BSd3v** [comment]
saw that this was addressed

**Comment by BSd3v** [comment]
Saw that that was to make it optional, the persistence prop is not available for inputs.

**Comment by snehilvj** [comment]
@BSd3v can you please elaborate?

**Comment by snehilvj** [comment]
You seem to be using it incorrectly. Refer to the docs here: https://dash.plotly.com/persistence

**Comment by BSd3v** [comment]
Persistence is a prop available for dmc? I couldn’t see it in docs.

**Comment by BSd3v** [comment]
@snehilvj,

`TypeError: The `dash_mantine_components.TextInput` component (version 0.11.0a2) with the ID "facet_col_wrap" received an unexpected keyword argument: `persistence`
Allowed arguments: className, debounce, description, disabled, error, icon, iconWidth, id, inputWrapperOrder, label, m, mb, ml, mr, mt, mx, my, name, p, pb, pl, placeholder, pr, pt, px, py, radius, required, rightSection, rightSectionWidth, size, style, styles, sx, t`

When trying to use persistence=True

**Comment by snehilvj** [comment]
Thanks @BSd3v for reporting this. I missed to add persistence in text inputs. Will be available in the next release.
