### ISSUE TITLE
Black bars in MultiSelect Dropdown window

### ISSUE THREAD

**Issue by Tomax77** [snehilvj/dash-mantine-components#113]
I've been faced with the problem, that my Dropdown window shows black bars at the bottom an on the right side. This seems not to be related with used CSS. How can I solve this problem? 
Beside of the problem this is a really fantastic component.

![Bildschirmfoto 2022-11-17 um 17 28 59](https://user-images.githubusercontent.com/13718275/202503786-99e90a9c-8570-4669-aa81-437928bfbe79.png)

**Comment by snehilvj** [comment]
Hi @Tomax77, wrap your app in dmc.MantineProvider to resolve this issue.

```python
app.layout = dmc.MantineProvider(
    withGlobalStyles=True,
    withNormalizeCSS=True,
    children=[...],
)
```

**Comment by Tomax77** [comment]
Tried to wrap my Bootstrap approach within Mantine Provider, but that doesn't change anything regarding the black bars. Did I make a mistake?

`app.layout = dmc.MantineProvider(
    withGlobalStyles=True,
    withNormalizeCSS=True,
    children=[
        dbc.Row(dbc.Col(title,width=12)),
        dbc.Row(dbc.Col(form_content, width=12)),
        ]
)`

**Comment by snehilvj** [comment]
Closing this because of no response.
