### ISSUE TITLE
dmc.TextInput() has "search" type but no data input for it to search from.

### ISSUE THREAD

**Issue by wakojako49** [snehilvj/dash-mantine-components#115]
Mantine JS has a component called [Autocomplete](https://mantine.dev/core/autocomplete/) which seems similar to `dmc.TextInput()`, which has a search "type". I think the only thing that it needs is a data input that [Autocomplete](https://mantine.dev/core/autocomplete/) also has. Such that the code would look like this.

```
dmc.TextInput(
     style={"width": 200},
     type="search",
      label="Your favorite framework/library",
      placeholder="Pick one",
      data=['React', 'Angular', 'Svelte', 'Vue'],
     dropdownPosition="bottom"
),
```

Not sure if this is worthwhile but since we're at it maybe allow data to be a list of a dicts. So that we can have something like "Custom Item Components" section in Mantine JS.

```
characterList = [
  {
    image: 'https://img.icons8.com/clouds/256/000000/futurama-bender.png',
    label: 'Bender Bending Rodríguez',
    description: 'Fascinated with cooking, though has no sense of taste',
  },

  {
    image: 'https://img.icons8.com/clouds/256/000000/futurama-mom.png',
    label: 'Carol Miller',
    description: 'One of the richest people on Earth',
  },
  {
    image: 'https://img.icons8.com/clouds/256/000000/homer-simpson.png',
    label: 'Homer Simpson',
    description: 'Overweight, lazy, and often ignorant',
  },
  {
    image: 'https://img.icons8.com/clouds/256/000000/spongebob-squarepants.png',
    label: 'Spongebob Squarepants',
    description: 'Not just a sponge',
  },
]

dmc.TextInput(
     style={"width": 200},
     type="search",
      label="Choose employee of the month",
      placeholder="Pick one",
      data=characterList,
     dropdownPosition="bottom"
),
```

**Comment by snehilvj** [comment]
Thanks @wakojako49 for reporting this. I think it's better to have a dedicated AutoComplete component. I'll work on adding it in the next release. 

> Not sure if this is worthwhile but since we're at it maybe allow data to be a list of a dicts. So that we can have
> something like "Custom Item Components" section in Mantine JS.

I'd rather have components like these and many others (useful combinations of various Mantine components) in a separate package, something like `dmc-extra-components`. I don't know if I'll be working on it though - open to the community.
