### ISSUE TITLE
DatePicker and DateRangePicker minDate and maxDate properties are set one day prior to specified

### ISSUE THREAD

**Issue by yuribr84** [snehilvj/dash-mantine-components#117]
## Enviroment

- Python 3.10.4
- `pip list | findstr dash`
```
dash                           2.7.0
dash-bootstrap-components      1.2.1
dash-core-components           2.0.0
dash-html-components           2.0.0
dash-mantine-components        0.10.2
dash-table                     5.0.0
```

- Same on all browsers I tested:
  - Chrome 107.0.5304.107
  - Firefox 102.5.0esr (64-bit)

## Bug description
When setting the minDate and maxDate properties on a DatePicker or a DateRangePicker component, the enabled dates displayed at runtime are one day prior to the dates specified. This issue can be replicated in the first example [here](https://dash-mantine-components.herokuapp.com/components/datepicker) by attempting to select the min or max date in the DatePicker and noticing the available options for min and max are in fact one day prior to specified.

### Affected components
- DatePicker 
- DateRangePicker 

### Screenshot
![image](https://user-images.githubusercontent.com/29901745/204395831-0ea2b74e-a789-4764-bb14-f190eb98fb16.png)

## Reference
This bug may be related to issue #33 or to timezone settings.

**Comment by snehilvj** [comment]
@I'm not able to reproduce this issue on my end. Can you try to reproduce it with the latest dmc?

**Comment by yuribr84** [comment]
I can confirm the bug no longer exists in version 0.12.1. Thanks for the feedback.
