### ISSUE TITLE
Docs on selectOnBlur

### ISSUE THREAD

**Issue by Lxstr** [snehilvj/dash-mantine-components#118]
Just wondering exactly what this feature does? I could not find any reference to it other that "Select highlighted item on blur." which I don't quite understand.

Thanks!

**Comment by datenzauberai** [comment]
You can highlight items in a Select menu using the arrow keys or the search feature without actually selecting them. To select a highlighted item, press Enter or click on it with your mouse. If you navigate away from the Select control (e.g., by pressing Tab or clicking elsewhere), the selection will not change. However, if `selectOnBlur` is enabled, leaving the component will select the currently highlighted item.

Caveat: it seems to me that the selectOnBlur property for ComboBox like components has been removed from DMC with the 0.14 release (I think it's still supported by upstream Mantine).

0.12.1:
https://github.com/snehilvj/dash-mantine-components/blob/1024af5a2940e23e1499c5a00c3129502640bc25/src/ts/props.ts#L382

current:
https://github.com/snehilvj/dash-mantine-components/blob/3d19642916ab597f8145bdc5fa45d4a5d5a8f429/src/ts/props/combobox.ts#L18

I guess we can close this one as long as the property is missing.

**Comment by AnnMarieW** [comment]
Thanks for the explanation @datenzauberai 

It appears that the `selectOnBlur` prop has been removed from the upstream Mantine library starting in V7.

Here is more information from the release notes https://github.com/mantinedev/mantine/blob/master/changelog/7.0.0.md#combobox-component and worth repeating here:



> ## Combobox component
>
> The new [Combobox](https://mantine.dev/core/combobox) component allows building custom select, autocomplete, tags input, multiselect and other
similar components. It is used as a base for updated [Autocomplete](https://mantine.dev/core/autocomplete), [Select](https://mantine.dev/core/select),
[TagsInput](https://mantine.dev/core/tags-input) and [MultiSelect](https://mantine.dev/core/multi-select) components.
>
>[Combobox](https://mantine.dev/core/combobox) is very flexible and allows you to have full control over the component rendering and logic.
Advanced features that were previously implemented in [Autocomplete](https://mantine.dev/core/autocomplete), [Select](https://mantine.dev/core/select)
and [MultiSelect](https://mantine.dev/core/multi-select) are now supposed to be implemented with [Combobox](https://mantine.dev/core/combobox) instead.
>
>You can find 50+ `Combobox` examples on [this page](https://mantine.dev/combobox).



Note the 50+ examples are excellent, and most are not included in the docs.  It include an example of how to recreate the `selectOnBlur` functionality and other props that were removed in V7, like `createable`  I'm going to close this topic for now and open  a new one to include a broader topic of how to implement more `Combobox` features.
