### ISSUE TITLE
dmc.Tooltip image instead of label text

### ISSUE THREAD

**Issue by NovakApis** [snehilvj/dash-mantine-components#121]
Is it possible for the dmc.Tooltip component to display images or other custom content, or only text?

**Comment by snehilvj** [comment]
Hi @NovakApis, you can use dmc.HoverCard available in version 0.11.0a3 (note that it's an alpha release). Temporary docs for the alpha can be found here: https://dmc-docs-pr-26.onrender.com/components/hovercard.
