### ISSUE TITLE
Documentation status for ThemeSwitcher

### ISSUE THREAD

**Issue by jajberni** [snehilvj/dash-mantine-components#123]
The ThemeSwitcher component used in the documentation repo is really useful and it would be great to include it in the documentation. 

https://github.com/snehilvj/dmc-docs/blob/b03e142ff67b99262f452af088c802847d71252e/lib/appshell.py#L113 

Any plans for documenting this functionality and providing some example? 

Thank you in advance!

**Comment by snehilvj** [comment]
ThemeSwitcher component was custom made for the documentation only so it was removed from the latest dmc version. Have a look at the latest implementation here: https://github.com/snehilvj/dmc-docs/blob/main/lib/appshell.py#L126-L135.
Custom components like these belong in a different package, something like: dmc-extra-components.
