### ISSUE TITLE
dmc.Group no longer has directon arg

### ISSUE THREAD

**Issue by dwassner** [snehilvj/dash-mantine-components#124]
I was unpleasantly surprised to see for the newest update that direction='row' and direction='column are not included, and are no longer stated in the docs.

It doesn't appear that these were combined into any other args, such as 'align'.

I personally use dmc.Group in every app I build, and always use the 'direction' arg - I would have to guess that others are similar with using the argument.

**Comment by yaszin** [comment]
Use [Stack](https://mantine.dev/core/stack/) component instead for vertical stacks
