### ISSUE TITLE
dmc.TimelineItem throws React Error when specifying bullet attribute

### ISSUE THREAD

**Issue by rick643charts** [snehilvj/dash-mantine-components#126]
After upgrading to the latest release (0.11.0), I'm receiving the following React Error when specifying the `bullet` parameter of the `dmc.TimelineItem` component:

> Objects are not valid as a React child (found: object with keys {namespace, props, type}). If you meant to render a collection of children, use an array instead.

For simplicity's sake, see the following reproducible example:

```
dmc.Timeline([

    dmc.TimelineItem(
        bullet=[
            dmc.Avatar(src='https://e7.pngegg.com/pngimages/799/987/png-clipart-computer-icons-avatar-icon-design-avatar-heroes')
        ],
        title=i
    )

for i in [1,2,3]])
```

**Comment by snehilvj** [comment]
Fixed, will be released in 0.11.1.
