### ISSUE TITLE
While the callback is firing, in the order versions, the button was disabled. In the current version, it is not.

### ISSUE THREAD

**Issue by sohibjon07012001** [snehilvj/dash-mantine-components#128]
hello everyone, I have now updated dash-mantine-components to a new version and in the previous version there was such an opportunity when in the button component on Output (“children”) I returned dash.no_update then the button became disable and it was loaded, but in the new version of the library It doesn’t happen.

**Comment by snehilvj** [comment]
Hi @sohibjon07012001, yes, it happened in the earlier versions but it was removed in the recent versions. Use https://dash.plotly.com/background-callbacks to achieve the same behaviour.

**Comment by sohibjon07012001** [comment]
we do not expect this feature in future versions?


пн, 2 янв. 2023 г. в 18:27, Snehil Vijay ***@***.***>:

**Comment by snehilvj** [comment]
No

**Comment by sohibjon07012001** [comment]
Yes, I agree with you, it would be cool to return this opportunity

ср, 4 янв. 2023 г., 19:31 Snehil Vijay ***@***.***>:

**Comment by snehilvj** [comment]
Starting with dash version 2.9.2, duplicate callback outputs are possible, which enables the discussed use case without any intervention in dmc.

Check out the Loading State section here: https://www.dash-mantine-components.com/components/button.

```python
import uuid
from time import sleep

import dash_mantine_components as dmc
from dash import html, callback, Output, Input
from dash_iconify import DashIconify

html.Div(
    [
        dmc.Button(
            "Load from database",
            id="loading-button",
            leftIcon=DashIconify(icon="fluent:database-plug-connected-20-filled"),
        ),
        dmc.Text(id="clicked-output", mt=10),
    ]
)


@callback(
    Output("loading-button", "loading", allow_duplicate=True),
    Input("loading-button", "n_clicks"),
    prevent_initial_call=True,
)
def update_loading_state(n_clicks):
    return True


@callback(
    Output("clicked-output", "children"),
    Output("loading-button", "loading"),
    Input("loading-button", "n_clicks"),
    prevent_initial_call=True,
)
def load_from_db(n_clicks):
    sleep(3)
    return str(uuid.uuid4()), False
```

**Comment by snehilvj** [comment]
Closed the issue by mistake!
