### ISSUE TITLE
HoverCard component with Anchor component as children not working as expected

### ISSUE THREAD

**Issue by subsurfaceiodev** [snehilvj/dash-mantine-components#129]
Hey there! We've noticed that, when including an Anchor component inside a HoverCard that directs to a file (e.g. in the assets folder) the download behavior is NOT the same as when the Anchor is not inside a HoverCard, which is the correct and expected behavior. Specifically, the download pop up shows TWICE when clicking the anchor, once with an empty file and the other with the correct one. Thanks!

**Comment by snehilvj** [comment]
Can you please share an MWE I can try out to reproduce this issue.

**Comment by snehilvj** [comment]
Closing it because of no response.
