### ISSUE TITLE
DateRangePicker setting openDropdownOnClear = False does not prevent dropdown from opening on clear

### ISSUE THREAD

**Issue by rick643charts** [snehilvj/dash-mantine-components#130]
Fairly straightforward issue here, setting `openDropdownOnClear = False` does not prevent the dropdown in `dmc.DateRangePicker` from opening on clear. Example below:

```
    dmc.DateRangePicker(id='date-range', initialMonth=date.today(), amountOfMonths=4, allowSingleDateInRange=True,
        icon=[DashIconify(icon="clarity:date-line")], placeholder='Limit date range...',
        clearable=True, openDropdownOnClear=False)
```

**Comment by snehilvj** [comment]
This was an issue in the upstream. It's fixed there so will also be available in dmc in the next release.
