### ISSUE TITLE
Datepicker does not use inputFormat settings with allowFreeInput

### ISSUE THREAD

**Issue by bufsim** [snehilvj/dash-mantine-components#131]
works only if i insert a date as  MM/DD/YYYY or set inputFormat='YYYY-MM-DD'

code example below

scripts = [
    "https://cdnjs.cloudflare.com/ajax/libs/dayjs/1.10.8/dayjs.min.js",
    "https://cdnjs.cloudflare.com/ajax/libs/dayjs/1.10.8/locale/it.min.js",
]
app = Dash(__name__, external_scripts=scripts)

app.layout =dmc.DatePicker(
    id="it-date-picker",
    label="data",
    allowFreeInput=True,
    inputFormat='DD/MM/YYYY',
    locale="it",
    style={"width": 200},
)

**Comment by snehilvj** [comment]
sorry, I'm not able to understand the problem, can you please elaborate? Thanks.

**Comment by bufsim** [comment]
I apologize if I was unclear. With the datepicker set as I wrote above, if I enter the date using the keyboard it is not entered according to the DD/MM/YYYY format. MM/DD/YYYY is entered.
as example, if i write 26/09/1972 and press enter in the field is written 01/02/2001. If i write 02/03/2020, in the field is written 03/02/2020

**Comment by snehilvj** [comment]
Understood now. It's a bug in Mantine v5 but has been fixed in one of the v6 alphas, so it will be available to dmc users when dmc is migrated to use Mantine v6.
