### ISSUE TITLE
datepicker disabledDates not working correctly.

### ISSUE THREAD

**Issue by jcuypers** [snehilvj/dash-mantine-components#137]
defining a disabledDate on a datepicker has a correct visual representation and behavior until you actually make a date selection.  After that the, disabled date it's visual appearance  is removed and cannot be restored again, even by resetting the selected date.

The issue is not only the visual representation of not being selectable, but it becomes actually selectable as an action

0.11.1

```
app.layout = dmc.DatePicker(
        id="date-picker",
        disabledDates=['2023-01-04'],
        description='test',
        style={'width': 200},
    ) 
```

**Comment by snehilvj** [comment]
Thanks @jcuypers for reporting, this has been fixed. Will be available in the next release.
