### ISSUE TITLE
Examples for all components are needed

### ISSUE THREAD

**Issue by Karan-S-Mittal** [snehilvj/dash-mantine-components#14]
Hi,
I was going through Readme and none of the examples are present right now. 
This is an amazing package @snehilvj. Thanks for creating it. 
I would like to help with examples of things if you will allow me.
Thanks and Regards,
Karan

**Comment by snehilvj** [comment]
Hi @Karan-S-Mittal thanks for your interest in this project. It was a mistake removing examples before I had a better place to put them. I moved the examples to [dmc-demo](https://github.com/snehilvj/dmc-demo/tree/dev) (currently in development).
This is how it will look once I'm done with all the components. I think this would be a better place to host some interactive examples along with the code to make them work (similar to dash bootstrap components).
<img width="1904" alt="dmc-demo" src="https://user-images.githubusercontent.com/91216500/147601631-395441e0-c8ab-4ccf-82be-6a320c51b374.png">
I'll put a comment in this thread once the first draft is released. I'd be very happy to have you contribute in this. Just give me some more time to finish this draft.

**Comment by snehilvj** [comment]
These are the components I'm done with so far and have released on Heroku. https://dash-mantine-components.herokuapp.com/

**Comment by Karan-S-Mittal** [comment]
Thank you @snehilvj for such a fast response. I am very excited to work on this.
I was also maintaining the [dash-daq](https://github.com/plotly/dash-daq/) package and a big fan of plotly.

**Comment by snehilvj** [comment]
Closing this issue now, as I have created a new project for adding docs/examples: [dmc-docs](https://github.com/snehilvj/dmc-docs).
