### ISSUE TITLE
MultiSelect - Ability to limit number of selected values being displayed

### ISSUE THREAD

**Issue by MPanek6** [snehilvj/dash-mantine-components#143]
Add the ability to specify the maximum number of rows of selected values to be displayed inside of the MultiSelect. Currently if hundreds of values are selected then the MultiSelect can grow extremely large thus taking up a lot of the page. 

Alternatively add the ability for a maximum number of displayed values to be specified as a pose to rows. The underlying ‘value’ should not be changed

**Comment by snehilvj** [comment]
How will the multiselect be useful if the user can't see the selected options? How will they interact with it? This seems more like a use case for a check list dropdown.

**Comment by MPanek6** [comment]
Hi, i submitted this as in my use case of the multiselect, the user has the ability to select any amount of values from > 10000 options. If for example they select 30, the multiselect grows extremely large filling most of the page. Ideally in instances such as this, the multiselect would display a message and when the multiselect is clicked on, it would expand to show all the selected values

**Comment by snehilvj** [comment]
That is not how multiselect should be used in my opinion. It's a use case for a check list dropdown like the below. If at all its to be implemented within the scope of dmc, it should be part of a different package called dmc-extra-components.

<img width="517" alt="Screenshot 2023-04-07 at 4 46 39 PM" src="https://user-images.githubusercontent.com/91216500/230599978-7af8bda3-6c6e-4172-8291-2571bf05f413.png">
