### ISSUE TITLE
DatePicker css  is broken in 0.11.x

### ISSUE THREAD

**Issue by thomasthebaker** [snehilvj/dash-mantine-components#144]
I've just upgraded to 0.11.1 and found that the DatePicker view renders the calendar outside of the popup. I've checked and the same issues is in 0.11.0 but if I go back to 0.10.2 the calendar popup renders correctly. Is there a change to css?

0.10.2
![image](https://user-images.githubusercontent.com/1649610/215113291-bb323a71-d244-4d73-81cc-299205d3e925.png)

0.11.0 and 0.11.1
![image](https://user-images.githubusercontent.com/1649610/215113420-efefd1e8-15ac-45ce-abb6-446990e8cbf8.png)

For reference this is wrapped in a Dash Design Kit ControlItem but going back to 0.10.2 fixes the issue:

```
# roughly what's in the full layout
html.Div([
ddk.ControlCard(orientation="horizontal", 
                           children=[
                           ddk.ControlItem(dmc.DatePicker(
                                  id="sigex-enddate",
                                  #initialLevel="date",
                                  inputFormat="YYYY-MM-DD",
                                  allowFreeInput=True,
                                  clearable=False,
                                  persistence=True,
                                  size="sm"), 
                               width=15)
                              ])
])
```

**Comment by snehilvj** [comment]
It seems to be caused by some conflicting css, maybe due to ddk. Can you test it without ddk and share the reproducible example?

**Comment by snehilvj** [comment]
Closing for no response and seems to be an incompatibility issue with ddk.

**Comment by milunova** [comment]
@thomasthebaker I had the same issue and solved it by setting style={'max-width':'100vw'} for the datepicker

**Comment by thomasthebaker** [comment]
@milunova thank you for the tip. I haven’t had a chance to experiment further but I’ll try that out this week.

**Comment by milunova** [comment]
@thomasthebaker FYI, I feel like I am going crazy but this solution is no longer working. Instead, I now have a css file in assets with the following entry which solves it. Hopefully @snehilvj can implement a permanent fix!

`.mantine-1nw5k7j {
max-width:100vw;
}`
