### ISSUE TITLE
Notification Component Not Working

### ISSUE THREAD

**Issue by amazighy** [snehilvj/dash-mantine-components#149]
The examples you have on the docs about the notification components are not working

**Comment by snehilvj** [comment]
Did you wrap your app in NotificationsProvider? If you did, and its still not working, please share an MRE.

**Comment by amazighy** [comment]
Yes, I did forget to wrap my app in the NotificationsProvider,  it works now. Thank you so much for responding and for all you do. Dash Mantine is simply fantastic!
