### ISSUE TITLE
'spacing' arg for dmc.Group is broken for 0.11.1

### ISSUE THREAD

**Issue by dwassner** [snehilvj/dash-mantine-components#151]
Per the docs:
- spacing (number; optional):
    Space between elements.

but using a string, int, or the older convention of 'sm', 'lg', etc has no impact.

**Comment by snehilvj** [comment]
@dwassner can you please share an MRE? I am not able to reproduce this issue.

**Comment by snehilvj** [comment]
Closing this for no response.
