### ISSUE TITLE
setting check=True doesn't work in CheckboxGroup

### ISSUE THREAD

**Issue by bingwork** [snehilvj/dash-mantine-components#153]
`import dash_mantine_components as dmc
from dash import html, Output, Input, callback, Dash

app = Dash()

app.layout = html.Div(
    [
        dmc.CheckboxGroup(
            id="checkbox-group",
            label="Select your favorite framework/library",
            description="This is anonymous",
            orientation="horizontal",
            withAsterisk=True,
            offset="md",
            mb=10,
            children=[
                dmc.Checkbox(label="React", value="react", checked=True),
                dmc.Checkbox(label="Vue", value="vue"),
                dmc.Checkbox(label="Svelte", value="svelte"),
                dmc.Checkbox(label="Angular", value="angular"),
            ],
        ),
        dmc.Text(id="checkbox-group-output"),
    ]
)

@callback(Output("checkbox-group-output", "children"), Input("checkbox-group", "value"))
def checkbox(value):
    return ", ".join(value) if value else None

app.run_server()
`

I set React checked=True, but it's not display as expected.

<img width="382" alt="image" src="https://user-images.githubusercontent.com/13247659/222657108-936b147a-0b17-439d-bd6f-7ba2060715a6.png">

@jcuypers could you help to take a look, thanks!

**Comment by snehilvj** [comment]
You need to use the `value` prop when using CheckboxGroup component. `checked` prop is useful only when using a single Checkbox component.
