### ISSUE TITLE
Not setting checked for Checkbox results in property being None in callback. 

### ISSUE THREAD

**Issue by Lucas-Steinmann** [snehilvj/dash-mantine-components#154]
Following minimal script might highlight the problem.

To reproduce the problem run the app and only hit the "Start"-Button.
The button for which `checked` was not set, will have state `checked=None`.

But the documentation says:

> - checked (boolean; default False):
>     State of check box.

This might be intended behaviour, to enable checking if a user even touched the checkbox.
So two possible fixes could be:

-  extend the documentation to reflect this behaviour
- fix the issue in the code, such that False is returned (sadly, this is out of my knowlegdge of react currently)

```
import dash
from dash import html, State, Input, Output
import dash_mantine_components as dmc


app = dash.Dash()
server = app.server
app.layout = html.Div([
    dmc.Checkbox(id="checkbox-default", label="Default"),
    dmc.Checkbox(id="checkbox-false", label="False", checked=False),
    dmc.Button("Start", id="start-button"),
    dmc.Text('', id='text-output'),
    dmc.Text('', id='text-output'),
])

@app.callback(
    inputs=dict(n_clicks=Input('start-button', 'n_clicks')),
    state=dict(
        checked_default=State('checkbox-default', 'checked'),
        checked_false=State('checkbox-false', 'checked')
    ),
    output=Output('text-output', 'children'),
)
def render_content(n_clicks, checked_default, checked_false):
    if not n_clicks:
        return dash.no_update
    return html.Ul([
        html.Li(f"'checked' not set --> {checked_default}"),
        html.Li(f"'checked=False' -> {checked_false}")
    ])


if __name__ == '__main__':
    app.run_server(debug=False)

```

Best,
Lucas

**Comment by snehilvj** [comment]
That's how dash props work, nothing I can do about it. But yeah I have taken care of the docs. You won't see default False after the next release.
