### ISSUE TITLE
Modal does not cover header and side bar

### ISSUE THREAD

**Issue by pbesson-invn** [snehilvj/dash-mantine-components#155]
From version 0.12.0, opening a modal does not cover header and side bar:

![image](https://user-images.githubusercontent.com/8382348/223405455-a225f3f3-3432-4f04-9f1b-68d4cd522939.png)

**Comment by snehilvj** [comment]
It was a z-index problem, which has been corrected in the docs. Users will have set this property accordingly while using these components in their apps.
