### ISSUE TITLE
[Feature Request] NavbarSection, Box, Flex, Collapse Components

### ISSUE THREAD

**Issue by milind** [snehilvj/dash-mantine-components#157]
Have loved playing around with the AppShell component that you've introduced into this library as it makes structuring my applications much cleaner. Would love if you could add in a wrapper for the Navbar.Section component at some point as without it is a bit of a pain to use the Navbar component and removes a bit of the readability of my code. I also think that having access to the Box component would make the MediaQuery component more useful. And finally, the addition of the Flex and Collapse components should round out all of the components necessary in order to create pretty advanced dashboard layouts. I might try to see if I have some time next weekend to poke around in your code and see whether I might be able to help on wrapping some of these components myself. Cheers!

**Comment by Kevinckyy** [comment]
Is there any progress on collapse components, especially a collapsable card? :pray:

**Comment by insilications** [comment]
Collapse element like dash_bootstrap_components would be nice

**Comment by snehilvj** [comment]
These components have all been added in the upcoming version of dmc.
