### ISSUE TITLE
Doc: add links for grouping elements to the main page

### ISSUE THREAD

**Issue by sergei3000** [snehilvj/dash-mantine-components#158]
In the documentation CheckboxGroup, ChipGroup and DateRangePicker docs are hidden inside Checkbox, Chip and DateRange pages respectively. I implemented my own date range code before finding out there is DateRangePicker in the library. And created some workarounds in my code to work with groups of checkboxes because I didn't know CheckboxGroup existed.

I am suggesting to add links to these elements to the "Inputs" section in the navigation bar on the left side of the main page so that anyone new to the library would know from the start which input elements they have at hand. If there's any other hidden things like the three I mentioned, they should be added to the navbar as well imho.

**Comment by snehilvj** [comment]
Thanks for the feedback. Noted.
