### ISSUE TITLE
Documentation for the library

### ISSUE THREAD

**Issue by snehilvj** [snehilvj/dash-mantine-components#16]
Hi
I'm starting this thread as I need some help from the community in creating the documentation for the library.

I have started a project [dmc-demo](https://github.com/snehilvj/dmc-demo) for this, and its deployed [here](https://dash-mantine-components.herokuapp.com). The latest version that's been released is 0.2.1, but before I move on with further releases, I'd like to work on the documentation, without which, people can obviously not use it properly.

I am already looking at the docs for official dash components and the docs for dash bootstrap components.

If anyone has any suggestions for the docs or some resources I can use, or some pointers for starting out, please do provide them.

Thanks

@emilhe @Karan-S-Mittal

**Comment by emilhe** [comment]
I was faced with similar considerations, when I wrote the [`dash-leaflet` docs](http://dash-leaflet.herokuapp.com/). I ended up just creating a Dash app using bootstrap, but I am curios to know about other (better?) options. It's actually on my TODO list to try reimplementing the `dash-leaflet` docs using mantine components :)

**Comment by Karan-S-Mittal** [comment]
It's my first time writing Docs for the application. I would like to propose an idea, that we can develop docs similar to Dash-docs, where we can showcase components alongside their multiple use-cases. 
🙂 @emilhe, I am a big fan of your work and am so glad to be part of this conversation.

**Comment by snehilvj** [comment]
yeah, I had similar thoughts about this. I have been working on a draft, here it is. Please let me know your feedback.
https://user-images.githubusercontent.com/91216500/148086429-29e9ff68-6ecf-441e-88c4-e2f9acc0efa2.mp4

**Comment by snehilvj** [comment]
I have released a new version of the dmc library: 0.2.2, and the new [docs](https://dash-mantine-components.herokuapp.com/installation/).
Closing this issue now. Docs related things can be discussed in its own repo: [dmc-demo](https://github.com/snehilvj/dmc-demo).

**Comment by emilhe** [comment]
I think it looks very nice! I was just about to ask for a link to code and/or a live app to get a better sense of the feel of the docs. The only immediate thing that strikes me as no-so-nice is the "Loading..." part that shows when each time a click on a new component.
