### ISSUE TITLE
There is no source distribution on pipy

### ISSUE THREAD

**Issue by kozmaz87** [snehilvj/dash-mantine-components#160]
This is a minor inconvenience for some but those who would like to see conda convert work it would be helpful.

**Comment by snehilvj** [comment]
I can't maintain it on conda, it's too much effort. I did onboard it to conda in the past, but it stopped working and I don't think I'll tackle it again in the near future.

**Comment by snehilvj** [comment]
Okay I'll try to correct that in new releases.

**Comment by snehilvj** [comment]
Fixed.
