### ISSUE TITLE
[BUG] AppShell `React.ReactElement` Bug in 0.12.0

### ISSUE THREAD

**Issue by milind** [snehilvj/dash-mantine-components#162]
In the update from 0.11.1 to 0.12.0, the properties for `AppShell` appear to have been changed from requiring a `JSX.Element` to a `React.ReactElement`, which seems to break things. The following MWE works with 0.11.1 but not with 0.12.0 (paired with dash version 2.9.1). Thanks!

```python
from dash import Dash
import dash_mantine_components as dmc

app = Dash(
    __name__,
)
app.layout = dmc.AppShell(
    header=dmc.Header(height="50px"),
    footer=dmc.Footer(height="50px"),
    children=dmc.Text("Some placeholder Text"),
)

if __name__ == "__main__":
    app.run_server(debug=True)
```
Additionally, there appears to be a separate issue wherein the content of the actual container is not properly aligned based on the configuration of the other props, but I can raise a separate issue for that as well if you'd prefer. (I believe that the core Mantine package handles this alignment automatically, but I could be mistaken).

**Comment by snehilvj** [comment]
Thanks for pointing this out. Fixed.

**Comment by snehilvj** [comment]
You can create separate issues for the alignment part.
