### ISSUE TITLE
[BUG] Mantine Select `creatable` requires `onCreate`

### ISSUE THREAD

**Issue by milind** [snehilvj/dash-mantine-components#164]
Hey! Apologies for peppering the issues section with the bugs that I stumble upon, but figured that I would document each of them for you to address at your convenience. According to the [Mantine select component docs](https://mantine.dev/core/select/#creatable), the `onCreate` prop is required in order to use the created prop. I'm actually not sure how to go about adding in JS functionality from within Dash, but I think that the newly open-sourced AG-Grid component has found a way to do this, so might be worth taking a look into that repository whenever you get the chance. Until then, might be worth it to just comment out that prop for the time-being. Thanks!

**Comment by snehilvj** [comment]
Hey no worries at all. You are contributing in making this library better, thanks for that!
Now your problem, you don't have to worry about the onCreate method. Just set the creatable and searchable props to True and done. I will add a section in the docs. Also, right now the `data` prop is not updated when new options are created but I have released a fix which will be available in the next release.
