### ISSUE TITLE
Feature request: Multiple DatePicker

### ISSUE THREAD

**Issue by claesnn** [snehilvj/dash-mantine-components#165]
Hi,

Is it possible to get the Mantine feature to select type="multiple" for the DatePicker?

[https://mantine.dev/dates/date-picker/#multiple-dates](url)

Thanks,
Claes

**Comment by milind** [comment]
I believe that that's a new feature in Mantine 6.0+ (they completely revamped the date components in that major version release) if I'm not mistaken, and dash-mantine-components is currently at Mantine version 5.10.5, so would need to address any breaking changes associated with the major release upgrade before adding in that prop.

**Comment by snehilvj** [comment]
yes @milind is right. dmc right now is based on Mantine's last v5 release. This will be automatically available when dmc moves to Mantine v6.
