### ISSUE TITLE
Consistent Styling for Select and MultiSelect

### ISSUE THREAD

**Issue by milunova** [snehilvj/dash-mantine-components#166]
When Select required prop is set to True, there is a red box around the dropdown. When Multi Select is required, there is an asterisk but no red box around the dropdown. Is there a way to achieve consistent styling? I have attempted to set the error however the thickness of the red box around the dropdown is different.

**Comment by snehilvj** [comment]
Dash includes some css by default which causes the ugly red box when you set the required prop to True. Use this in your app to counteract it.
```css
input:invalid {
    outline: none !important;
}
```

**Comment by snehilvj** [comment]
Updated it in the docs too.
