### ISSUE TITLE
DatePicker does not reset to None

### ISSUE THREAD

**Issue by ahdorneles** [snehilvj/dash-mantine-components#167]
I'm using the DatePicker component from dash-mantine-components version 0.11.1 and I noticed a weird behaviour DatePicker: value cannot be **reset to None:**

1. I build the component with value=None and then the DatePicker button is empty. 
2. Then imagine that an user picks a date. 
3. Then the user wants to make this date blank again - not clicking in the clearable x button, but through a "Reset" button - and this is not possible. 
-> If I send None or "" as a value for the DatePicker it keeps showing the previous picked date. If I send a 'YYYY-DD-MM' date string it updates, if I send any other string it updates and say "Invalid date". 
-> Even if I completely build the DatePicker again with a None value but with the same id the previous picked date is still there. 

Have any of you faced this issue before? Any tips on resetting DatePicker date values? Thank you very much!
```
@callback(
    output=dict(
        production_date=Output("query-interface-production-date", "value")
    ),
    inputs=dict(
        reset=Input("reset", "n_clicks"),
        prod_date=State("query-interface-production-date", "value"),
    ),
    config_prevent_initial_callbacks=True,
)
def return_to_query_manager(reset: int):
    if reset is not None:
       return dict(production_date=None) ```

**Comment by milind** [comment]
So I just want to make sure that I'm understanding the problem that you're having properly. Does the below MWE represent the functionality that you desire:

```python
from dash import Dash, callback, Input, Output
import dash_mantine_components as dmc

app = Dash(
    __name__,
)
app.layout = dmc.Stack(
    [
        dmc.DatePicker(
            id="date",
        ),
        dmc.Button("Reset Date", id="reset"),
        dmc.Text(id="default"),
    ]
)


@callback(
    Output("date", "value"),
    Input("reset", "n_clicks"),
    prevent_initial_call=True,
)
def reset_value(_):
    return None


@callback(
    Output("default", "children"),
    Input("date", "value"),
)
def get_value(value):
    return str(value)


if __name__ == "__main__":
    app.run_server(debug=True)
```

**Comment by milind** [comment]
Ah actually now that I look at the example I posted, it seems as though the actual value itself updated, as you should see in the callback output, but the visual display of the previously-selected date does not appear to go away.

**Comment by snehilvj** [comment]
Fixed. Will be available in the next release.
