### ISSUE TITLE
Add n_submits property to TextInput

### ISSUE THREAD

**Issue by jacobswe** [snehilvj/dash-mantine-components#173]
The [dcc.Input](https://dash.plotly.com/dash-core-components/input) component has an n_submits property that increments when the <kbd>Enter</kbd> key is pressed while the input has focus. This would be useful for example in the TextInput or PasswordInput to quickly capture the values without requiring a separate button push (e.g., messaging). I'm happy to give this a shot if you can point me in the right direction.

**Comment by AnnMarieW** [comment]
Hi @jacobswe 

Thanks for raising this issue and doing the PR.  Sorry for the long delay.

We are looking into developing a comprehensive and consistent  way to add debounce to all the input and select components like in the dash-core-components and dash-boostrap-components libraries.  I'm going to close this and the related PR for now and so it can be combined with #87. 

Please feel free to chime in on that issue and if you are still interested in doing a PR and once we have a plan, I'd be delighted.

Thanks again for your contribution.,
