### ISSUE TITLE
Dark theme in plotly graphs

### ISSUE THREAD

**Issue by michelkok** [snehilvj/dash-mantine-components#174]
I love how the dark theme support works for all dmc components without any effort by wrapping the app in a `MantineProvider`.
However, I struggle to update the template of my plotly graph which is wrapped in a `dcc.Graph` component accordingly.

At the moment I change the `template` property of the `px.scatter` or `px.image` to the `plotly_dark` template using the callback that modifies the graph. However, this gives at least 2 problems:
1. The colors are different.
2. The dark scheme updates everything using a clienside callback (as happens in the dmc docs). The graph is not updated at that moment.

Next to this, it all feels a bit hacky to modify the template property with a callback manually.

Is there a better way to achieve this? E.g., is there a `dmc.Graph` component or something like that or another type of wrapper function?

**Comment by snehilvj** [comment]
No. There is currently no way to achieve the same color scheme in plotly graphs as dmc.
