### ISSUE TITLE
Problem with Checkbox

### ISSUE THREAD

**Issue by milunova** [snehilvj/dash-mantine-components#176]
When using dmc checkbox, there are two checks as can be seen in the image below:

![image](https://user-images.githubusercontent.com/99946963/231266222-f2f9589a-fbe8-4737-9896-41c769397325.png)

I was able to get rid of the green check by adding the CSS below however, that makes all dcc check marks transparent. Is there another way to solve this? Since I use select option in dash tables, I cannot make all checks transparent.

```
.ddk-container.ddk-container input[type=checkbox]:checked:before {
    color: transparent;
  } 
```

**Comment by snehilvj** [comment]
This seems to be caused by conflicting css from ddk.
