### ISSUE TITLE
Mantine Rich Text Editor Request

### ISSUE THREAD

**Issue by milunova** [snehilvj/dash-mantine-components#178]
Would love to be able to use mantine's rich text editor as part of this library! https://mantine.dev/others/tiptap/

**Comment by snehilvj** [comment]
Sorry, currently, I don't have the bandwidth to maintain this package.

**Comment by benweinberg89** [comment]
@AnnMarieW @snehilvj Is there any bandwidth to support this now?

**Comment by AnnMarieW** [comment]
Hi @benweinberg89 
This is a great component, but a big job to include it here.  I'd be open to a pull request though.
Could revisit this after the first major release is completed.  For more details see the [Roadmap](https://github.com/snehilvj/dash-mantine-components/discussions/377)
