### ISSUE TITLE
MultiSelect search strange behaviour

### ISSUE THREAD

**Issue by etiennecelery** [snehilvj/dash-mantine-components#183]
Hi, awesome work with this library, really takes Dash to the next level.

I am experiencing this strange behavior while searching a MultiSelect component wich has different values for its data attribute.

`dmc.MultiSelect(
    id='my-dropdown',
    data=[{'label': x, 'value': y} for x, y in zip(list1, list2)], # different values
    searchable=True,
`
<img width="695" alt="Screenshot 2023-04-25 at 15 56 24" src="https://user-images.githubusercontent.com/22829290/234388648-cc32fb2b-8366-4912-83bd-6a36c72603bd.png">

As you can see in the image, the search returns results that do not match the input.

Thank you

**Comment by snehilvj** [comment]
Please share an MRE.

**Comment by datenzauberai** [comment]
Missing MRE and more than a year old. @AnnMarieW Maybe this one could be closed?
