### ISSUE TITLE
Styling Drawer using style, styles {'drawer'}

### ISSUE THREAD

**Issue by BSd3v** [snehilvj/dash-mantine-components#187]
I was trying to style a drawer and adjust padding on the whole thing, I was unable to do so with:
`style={'padding':'15px'}`
`style={'padding':15}`
`styles={'drawer':{'padding': '15px'}}`
`styles={'drawer':{'padding': 15}}`

I ended up settling for:
`styles={'body':{'padding': 15}}`

**Comment by AnnMarieW** [comment]
@BSd3v I'm just reviewing old issues.  I expect this is no longer a problem?   

As of 0.14.0 `drawer` is not a selector.  `body` or `root` should work though.

I'm going to close this for now.  Feel free to re-open if you still have an issue with the current version :slightly_smiling_face:
