### ISSUE TITLE
`dmc.Switch`: changing `thumbIcon` on checked

### ISSUE THREAD

**Issue by plutonium-239** [snehilvj/dash-mantine-components#188]
As seen in https://mantine.dev/core/switch/#thumb-icon, we can have a changing thumb icon in the Mantine Switch.
But, unlike `offLabel` and `onLabel`, the icon is decided by `checked`.

> ```js 
> thumbIcon={
>   checked ? (
>     <IconCheck size="0.8rem" color={theme.colors.teal[theme.fn.primaryShade()]} stroke={3} />
>   ) : (
>     <IconX size="0.8rem" color={theme.colors.red[theme.fn.primaryShade()]} stroke={3} />
>   )
> }
> ```

This would be a welcome change,
One way would be to provide 2 options in the python API and then replicate the above behavior internally.

Here is a simple clientside callback workaround:
```python
dmc.Switch(
	thumbIcon=DashIconify(icon='bi:unlock-fill', width=16, id='switch_icon'),
	id='switch', 
	checked=True
)

dash_app.clientside_callback(
	"""
	function(checked) {
		if (checked) {
			return 'bi:unlock-fill';
		}
		return 'bi:lock-fill';
	}
	""",
	Output('switch_icon', 'icon'),
	Input('switch', 'checked')
)
```
This expects that you want to use enabled `thumbIcon` as `bi:unlock-fill` and disabled as `bi:lock-fill`.

**Comment by snehilvj** [comment]
Hi, this can't be supported in dmc at the moment. Using callbacks or some css tricks is the only way to go.
