### ISSUE TITLE
DatePicker can crash browser

### ISSUE THREAD

**Issue by ndrezn** [snehilvj/dash-mantine-components#189]
This is actually visible in the docs (https://www.dash-mantine-components.com/components/datepicker), try clicking this example:
![image](https://github.com/snehilvj/dash-mantine-components/assets/38958867/7c0dee4f-f6d1-4693-99ab-120851fdf3a1)

I see "Browser not responding" almost immediately.

Using Firefox.

**Comment by Rushclin** [comment]
Same problem

**Comment by snehilvj** [comment]
Hi all, this issue is known to me, and I'm trying my best to fix it. Thanks for the patience.

**Comment by Rushclin** [comment]
I used version  0.11 and it work good ✨

**Comment by snehilvj** [comment]
0.11.0 is based on Mantine v4
0.12.0 is based on Mantine v5 (which has the issue)

I've started working on migrating to Mantine v6, which doesn't seem to have this problem. I was waiting for Mantine v7 to be released (which is in alpha right now), but I guess it won't be released anytime soon.

**Comment by ndrezn** [comment]
Thanks @snehilvj!

**Comment by Werokajo** [comment]
Hi, I'm facing the same freezing issue. Any idea till when we can expect a fix or upgrade?

**Comment by snehilvj** [comment]
This has been fixed in the latest 0.13 alphas.
