### ISSUE TITLE
DatePicker allowFreeInput clear upon backspace and enter

### ISSUE THREAD

**Issue by BSd3v** [snehilvj/dash-mantine-components#190]
Good day,

I'm trying to clear the DatePicker value upon the user clearing the typed value when using `allowFreeInput`, clearing the typed input resets to the original value, does anyone have a way to have it clear?

```
from dash import Dash, html, dcc
import dash_mantine_components as dmc


app = Dash(__name__)

app.layout = html.Div(
    [
        dmc.DatePicker(allowFreeInput=True)
    ],
    style={"margin": 20},
)

if __name__ == "__main__":
    app.run_server(debug=True)
```

**Comment by AnnMarieW** [comment]
There is no longer a `allowFreeInput` prop, so I’m going to close this issue.
Note - there is a now a `clearable` prop in 0.14.4, so it will likely solve this issue.
