### ISSUE TITLE
How to create a multi-level menu

### ISSUE THREAD

**Issue by jwag59** [snehilvj/dash-mantine-components#192]
I'm new to DMC so maybe I don't understand this at all. But I tried creating a multi-level menu by using dmc.MenuItem entries as children of a parent dmc.MenuItem. I found 2 issues with this. 
1) Since the MenuItem component does not have a 'Title' or 'Label' option, if you want to provide children MenuItems there is no way to have both a label and children (since in the current implementation the label is normally provided as one of the children).
2) The lower level MenuItems are placed over the other existing menu items on the page, making them impossible to read.

Can someone point out what I'm doing wrong or how to create multi-level menus with DMC.
Below find the source code and screen shot of the created menu.

```
mmenu = dmc.Menu(
    [
        dmc.MenuLabel("Application"),
        dmc.MenuItem("Settings", icon=DashIconify(icon="tabler:settings")),
        dmc.MenuItem(icon=DashIconify(icon="tabler:message"),
                     children=[
                         dmc.MenuItem("Item1", icon=DashIconify(icon="tabler:photo")),
                         dmc.MenuItem("Item2", icon=DashIconify(icon="tabler:search")),
                         dmc.MenuItem("Item3", icon=DashIconify(icon="tabler:settings")),
                     ]
        ),
        dmc.MenuItem("Gallery", icon=DashIconify(icon="tabler:photo")),
        dmc.MenuItem("Search", icon=DashIconify(icon="tabler:search")),
        dmc.MenuDivider(),
        dmc.MenuLabel("Danger Zone"),
        dmc.MenuItem(
            "Transfer my data",
            icon=DashIconify(icon="tabler:arrows-left-right"),
        ),
        dmc.MenuItem(
            "Delete my account",
            icon=DashIconify(icon="tabler:trash"),
            color="red",
        ),
    ],
)
```

![image](https://github.com/snehilvj/dash-mantine-components/assets/22910903/4f44baab-831a-41e6-bdfe-c6aad556b9d8)

**Comment by snehilvj** [comment]
Multilevel menus are not supported.

**Comment by DWThayerMahan** [comment]
I managed to get limited functionality  by restarting the entire menu structure inside a menu item. i.e.
menu(
     MenuTarget()
     MenuDropdown(
          MenuItem()
          MenuItem(
               Menu(
                    MenuTarget()
                    MenuDropdown(
                         MenuItem()
                    )
               )
          )
     )
)

I did find that there are some issues implementing this. For instance, it seems to block the callback for dcc.upload elements. It worked fine with menuItems that do not have children that are just text and it allowed their callbacks
