### ISSUE TITLE
TimeInput's value is a datetime rather than time

### ISSUE THREAD

**Issue by RenaudLN** [snehilvj/dash-mantine-components#197]
For some reason, the value of the TimeInput component is a datetime (with today's date) rather than just time time part.

This makes it cumbersome to use downstream as one must remember to extract only the relevant bit from the time value.

**Comment by AnnMarieW** [comment]
Hey @RenaudLN 

It looks like this was fixed in the latest version, so I'll close this now.

Here is an example:

```python

import dash_mantine_components as dmc
from dash import Dash, _dash_renderer, Input, Output, callback, no_update
_dash_renderer._set_react_version("18.2.0")

app = Dash(external_stylesheets=dmc.styles.ALL)

app.layout = dmc.MantineProvider([
    dmc.TimeInput(
        label="Pick  time",
        id="time-picker"
    ),
    dmc.Text(id="container")
])

@callback(
    Output("container", "children"),
    Input("time-picker", "value")
)
def update(t):
    if t:
        return f"You selected {t}"
    return no_update

if __name__ == "__main__":
    app.run(debug=True)
```

![image](https://github.com/user-attachments/assets/22d57b4e-ce4e-4cf2-8430-d9695792ce32)
