### ISSUE TITLE
Can't set value for ColorPicker

### ISSUE THREAD

**Issue by ionutscorta** [snehilvj/dash-mantine-components#198]
The color picker example doesn't work in the latest version, if I copy/pasted the sample from the documentation: https://www.dash-mantine-components.com/components/colorpicker the picker always has white color by default.

**Comment by hannahker** [comment]
+1 - Would be great to be able to initialize the `ColorPicker` with something other than white.

**Comment by snehilvj** [comment]
This has been fixed in the latest 0.13 alphas.
