### ISSUE TITLE
Naming convention className or class_name

### ISSUE THREAD

**Issue by emilhe** [snehilvj/dash-mantine-components#21]
I noticed that [dash bootstrap components](https://dash-bootstrap-components.opensource.faculty.ai/docs/components/) have deprecated the `className` keyword in favor of `class_name`. Have you made any thoughts about which convention to follow, @snehilvj? If you end up choosing to follow that convention (i.e. to use `class_name`), I guess it would be better to make the switch sooner than later.

**Comment by emilhe** [comment]
Going though the components, I can see that `class_name `is already used consistently.

**Comment by snehilvj** [comment]
Yes I made the transition in the last release: 0.2.2
