### ISSUE TITLE
Min value of RangeSlider is None

### ISSUE THREAD

**Issue by dgmcrae** [snehilvj/dash-mantine-components#213]
I have a RangeSlider defined in my layout as follows using dash-mantine-components 0.12.1, with the various properties populated by callback:

`my_rangeslider = dmc.RangeSlider(id="placeholder", value=[], marks = [])`

My callback has the following outputs, where the supplied values of "min" and "max" are positive integers and "marks" is a list of dictionaries.:

`Output("placeholder", "min"), Output("placeholder", "max"), Output("placeholder", "marks")`

The RangeSlider renders in the layout with both handles at the minimum extreme of the range, and only the right handle able to be moved, without a bar linking the two handles. If I use the callback from the RangeSlider documentation to access the value property when I move the right handle, I get the following output:

'You have selected: [None, a positive integer]'

I have tried setting minRange either by callback or hardcoding, but it does not prevent the None value for the minimum end of the range.

Thank you for all work on dmc - it's a fantastic library!

**Comment by AnnMarieW** [comment]
Hi @dgmcrae 

Thanks for reporting and sorry for the delay.  In the current release, there are now defaults for `min` and `max` values.  However, it appears that the value prop is required.  If `value=[]` then the component doesn't render and there is an error. 


```
import dash_mantine_components as dmc
from dash import Dash, _dash_renderer
_dash_renderer._set_react_version("18.2.0")

app = Dash()

component = dmc.RangeSlider(
            id="range-slider",
            value=[],
            marks=[
                {"value": 20, "label": "20%"},
                {"value": 50, "label": "50%"},
                {"value": 80, "label": "80%"},
            ],
        )

app.layout = dmc.MantineProvider([
    component
])

if __name__ == "__main__":
    app.run(debug=True)


```
![image](https://github.com/user-attachments/assets/f49233fc-0c08-4d79-8bfb-7354afbf5b3c)
