### ISSUE TITLE
Data Property does not get saved for a multi page setup

### ISSUE THREAD

**Issue by sssaha1989** [snehilvj/dash-mantine-components#214]
Hello 
I am using the dash mantine Select component in a multi page application. I have the createable option True which allows me to create/add new option. However my application is multi-page application. So when I switch to a new page and then come to the original page that had the Select option - the data value does not say updated. That means the value that I created does not appear in the options of Select. I could not add that to the persistence option as the documentation says the persistance is only applicable for the value component.

**Comment by AnnMarieW** [comment]
Unfortunately the upstream Mantine library no longer has a `creatable` prop for the Select components, so this feature is not available as of dmc 0.14.0.

For anyone still using less than 0.14.0, you can persist the user-created options by including  `data` in the `persisted_props`: 

` persisted_props=["value", "data"],`

Here's a complete example using dmc=0.12.1:


```python

import dash
import dash_mantine_components as dmc
from dash import Dash, html, dcc
app = Dash( use_pages=True, pages_folder="")


select =  dmc.Select(
    id="creatable-select",
    creatable=True,
    searchable=True,
    style={"width": 200},
    data=["react", "flask"],
    persisted_props=["value", "data"],
    persistence=True
)


dash.register_page("home", layout="We're home!", path="/")
dash.register_page("page2", layout=select, path="/page2")


main_layout = html.Div(
    [
        html.H1("App Frame"),
        html.Div(
            [
                html.Div(
                    dcc.Link(f"{page['name']} - {page['path']}", href=page["path"])
                )
                for page in dash.page_registry.values()
                if page["module"] != "pages.not_found_404"
            ]
        ),
        dash.page_container,
    ]
)


app.layout = dmc.MantineProvider(main_layout)

if __name__ == "__main__":
    app.run(debug=True)



```
