### ISSUE TITLE
Theme's primaryColor is ignored

### ISSUE THREAD

**Issue by lucafaggianelli** [snehilvj/dash-mantine-components#216]
Hi,

In my app's theme I've set the primary color but I don't see this reflected in the components:

```py
dmc.MantineProvider(
        id="mantine-theme-provider",
        theme={
            "colorScheme": "light",
            "fontFamily": "'Inter', sans-serif",
            "primaryColor": "green",
        },
        inherit=True,
        withGlobalStyles=True,
        withNormalizeCSS=True,
        children=[]
)
```

And here the content of a Dash page:

```py
dmc.Button(
    "Github",
    leftIcon=DashIconify(icon="mingcute:github-fill"),
    size="lg",
)
```

This is what I get:

![image](https://github.com/snehilvj/dash-mantine-components/assets/4471043/c1484ac4-8262-4063-b8db-ab15bdac091e)

Based on https://mantine.dev/theming/colors/#primarycolor I would expect my button to be green, or did I misunderstood the meaning of primaryColor?

**Comment by datenzauberai** [comment]
This works as expected with the current version:

```
from dash import Dash, _dash_renderer
import dash_mantine_components as dmc
from dash_iconify import DashIconify

_dash_renderer._set_react_version("18.2.0")

app = Dash(external_stylesheets=dmc.styles.ALL)

app.layout = dmc.MantineProvider(
    dmc.Container(
        children=[
            dmc.Button(
                "Github",
                leftSection=DashIconify(icon="mingcute:github-fill"),
                size="lg",
            )
        ],
        style={"padding": "1rem"}
    ),
    theme={
        "primaryColor": "green",
    },
)

if __name__ == "__main__":
    app.run(debug=True)
```

<img width="332" alt="Bildschirmfoto 2024-09-08 um 14 43 02" src="https://github.com/user-attachments/assets/65339653-ced0-4d31-8b4e-d0de9b93f0ee">

**Comment by AnnMarieW** [comment]
Thanks for confirming this works now @datenzauberai 
I'll close this issue now :tada:
