### ISSUE TITLE
Carousel support [feature request]

### ISSUE THREAD

**Issue by Liripo** [snehilvj/dash-mantine-components#220]
Hello Developer:
No examples of Carousel found in the warehouse documentation.
Thank you.

**Comment by CNFeffery** [comment]
@Liripo https://fac.feffery.tech/AntdCarousel

**Comment by Liripo** [comment]
@CNFeffery Thanks, I'm using it now.

**Comment by snehilvj** [comment]
I've added Carousel, will be available in the next release.
