### ISSUE TITLE
[Request] How can I change the checkedIcon displayed on the left of dmc.Chip?

### ISSUE THREAD

**Issue by RainyBlue-w** [snehilvj/dash-mantine-components#223]
As shown in the picture, now the icon is a check mark, I want to change it to a filled circle. How can I make it?
I have found that there is a `checkIcon` API in styles-API, but there is noting about icon in the `component props`.
And I have tried to  change the `type` prop to `radio`, but failed.
![image](https://github.com/snehilvj/dash-mantine-components/assets/155552042/810bef60-c353-4c56-b716-49fb5b684e0e)
![image](https://github.com/snehilvj/dash-mantine-components/assets/155552042/7c1ba67f-e518-42f4-a769-ec28b5aa576c)

**Comment by datenzauberai** [comment]
You can use the icon property:

```python
from dash import Dash, _dash_renderer
import dash_mantine_components as dmc
from dash_iconify import DashIconify

_dash_renderer._set_react_version("18.2.0")

app = Dash(external_stylesheets=dmc.styles.ALL)

app.layout = dmc.MantineProvider(
    dmc.Container(
        dmc.Group(
            children=[
                dmc.Chip("Hello", icon=DashIconify(icon="ic:baseline-radio-button-checked")),
                dmc.Chip("World", icon=DashIconify(icon="ic:baseline-radio-button-checked"))
            ]
        ), style={"padding": "1rem"}
    )
)

if __name__ == "__main__":
    app.run(debug=True)
```

<img width="332" alt="Bildschirmfoto 2024-09-08 um 14 36 56" src="https://github.com/user-attachments/assets/cac50dbe-49dd-4641-b0c8-73487aa5a34c">

**Comment by AnnMarieW** [comment]
Thanks for the solution @datenzauberai :trophy:
