### ISSUE TITLE
'required' prop on select & multiselect not working

### ISSUE THREAD

**Issue by interactda** [snehilvj/dash-mantine-components#226]
Hi there, I would like my Multiselect and Select option to be mandatory, I see that there's 'required' prop option to realize this. However, after I add the prop, it doesn't seem to have any effect on the multiselect. Any idea how I can solve this? thank you.

`dmc.MultiSelect(
                    id="baseline-supervised-pipelines-select",
                    searchable=True,
                    clearable=True,
                    required=True,
                    withAsterisk=True,
                    nothingFound="No pipelines found.",
                    placeholder="Select pipelines to run.",
                    **PERSISTENCE_PROPS_SESSION,
                )`

<img width="524" alt="image" src="https://github.com/snehilvj/dash-mantine-components/assets/134859441/c1946d21-b94b-42d0-966c-42f70a9a0461">
<img width="937" alt="image" src="https://github.com/snehilvj/dash-mantine-components/assets/134859441/adc5021d-0bed-4a59-b1b4-2d346cdd69ee">

**Comment by snehilvj** [comment]
In terms of what users will see, required component only shows an asterisk against the label.
<img width="375" alt="Screenshot 2024-04-14 at 11 36 13 AM" src="https://github.com/snehilvj/dash-mantine-components/assets/91216500/efb97a1c-cdff-4ee4-b246-be8d830b5b09">
If you don't want to show label in your select, you can use the 'error' attribute with a custom client side callback.
Here's one example (though the callback is server side here):
https://www.dash-mantine-components.com/components/multiselect#invalid-state-and-error
<img width="523" alt="Screenshot 2024-04-14 at 11 37 51 AM" src="https://github.com/snehilvj/dash-mantine-components/assets/91216500/a2c7ce09-34c2-41f3-97e7-05c16978b2a6">
