### ISSUE TITLE
Example code for tabs and icons raises TypeError

### ISSUE THREAD

**Issue by corbinhaugen** [snehilvj/dash-mantine-components#229]
Both example code snippets for "Icons and Right Section" on https://www.dash-mantine-components.com/components/tabs raise a TypeError:

`TypeError: The 'dash_mantine_components.Tab' component (version 0.12.1) detected a Component for a prop other than 'children'
Did you forget to wrap multiple 'children' in an array?
Prop icon has value DashIconify(icon='tabler:message')`

**Comment by snehilvj** [comment]
This is probably because of an older version of dash. Closing this now.
