### ISSUE TITLE
[Bug] Issue accessing value of maxDate for DateRangePicker and DatePicker components

### ISSUE THREAD

**Issue by nadijagraca** [snehilvj/dash-mantine-components#230]
I'm encountering an issue with accessing the `maxDate` value for both the `DateRangePicker` and `DatePicker` components in certain scenarios.

For instance, when configuring the `DateRangePicker` as shown below, I face difficulty navigating to the month of July and selecting 1st of July. However, if I set `"2024-07-02"` as the `maxDate`, the July month becomes accessible.
```
dmc.DateRangePicker(
            minDate="2024-01-01", 
            value=["2024-01-01", "2024-03-01"]
            maxDate="2024-07-01",
            persistence=True,
            persistence_type="session",
        )
```

<img width="338" alt="Screenshot 2024-02-27 at 18 41 01" src="https://github.com/snehilvj/dash-mantine-components/assets/108531476/650658ed-dd39-44bf-93f1-fb1df20499db">

Also, if I choose `"2024-06-01"` as `maxDate`, I can select 1st of June from May calendar view but I still cannot navigate to the month of June on the calendar. 

<img width="326" alt="Screenshot 2024-02-27 at 19 17 08" src="https://github.com/snehilvj/dash-mantine-components/assets/108531476/da7006e8-d61d-4e7e-a6bd-75019a15f0d5">

**Comment by AnnMarieW** [comment]
Hi @nadijagraca 
It looks like you are using an old version of dmc.  There were a lot of changes to the date picker components in V14, which is based on the V7 Mantine library. 

I can't replicate this issue in the current release   0.14.4 :

```
from datetime import datetime, timedelta, date

import dash_mantine_components as dmc
from dash import Dash, _dash_renderer, Input, Output
_dash_renderer._set_react_version("18.2.0")

app = Dash(external_stylesheets=dmc.styles.ALL)

component = dmc.DatePicker(
            id="date-input-range-picker",
            minDate="2024-01-01",
            maxDate="2024-07-01",
            label="Date Range",
            description="Select a date range",
            type="range",
            value=["2024-01-01", "2024-03-01"],
            maw=300,
        )
app.layout = dmc.MantineProvider([
    component
])

if __name__ == "__main__":
    app.run(debug=True)


```
![image](https://github.com/user-attachments/assets/fdd64a76-339a-44ed-a246-0d82274478c4)


Since older versions are no longer supported, I'm going to close this issue for now.
