### ISSUE TITLE
[BUG] Using notifications along with an Interval results in endless re-triggering of notifications

### ISSUE THREAD

**Issue by j-m-mueller** [snehilvj/dash-mantine-components#233]
Whenever a notification is raised within an app that also contains an Interval component, the notification is re-raised whenever the interval triggers an app refresh. This results in notifications popping up again and again, regardless of whether they were already manually closed or have an autoClose set.

Minimal code example:

```
import dash
import dash_mantine_components as dmc

from dash import Dash, html, callback, Input, Output, dcc
from dash.exceptions import PreventUpdate


app = Dash(__name__)

server = app.server


app.layout = dmc.NotificationsProvider(
    [
        html.Div(
            [
                html.Div(id="notifications-container"),
                dmc.Button("Show Notification", id="notify"),
            ]
        ),
        dcc.Interval(
            id='interval-component',
            interval=5000,
            n_intervals=0
        )
    ]
)


@callback(
    Output("notifications-container", "children"),
    Input("notify", "n_clicks"),
    prevent_initial_call=True,
)
def show(n_clicks):
    if n_clicks:
        return dmc.Notification(
            title="Hey there!",
            id="simple-notify",
            action="show",
            message="Notifications in Dash, Awesome!",
            autoClose=2000
        )
    else:
        raise PreventUpdate


if __name__ == '__main__':
    app.run_server(debug=True)
```

**Comment by snehilvj** [comment]
Hi, the example seems incomplete.

**Comment by BSd3v** [comment]
Hello @j-m-mueller 

I wouldn't consider a notification issue with Hot Reloading a bug. Why is the app refreshing?

I have noticed that when I have hot reloading on and I've had notifications, they pop back up. But, this is an issue with how props are stored in dash and not dmc. 

Technically, the notification will always exist in the list components in dash. And thus, upon hot reload the app will try to rerender the components that exist in the browser.

**Comment by Tomer-EVM** [comment]
Hello!
I would like to reopen this bug report with the following example, adapted from the dash-multi-page-app-demos/multi-page-example1 directory in the great [demo repo](https://github.com/AnnMarieW/dash-multi-page-app-demos/).

In my example the notification appears to be created without the callback firing.
To prevent xy problems...my actual usecase is to refresh a dash leaflet map with new data every minute when on the 'live' page but I see the notifications on every page of the app.

Expected behaviour:
When not on the random page, we should see no notifications

Actual behaviour:
Regardless of the page, we see notifications get created every 5 seconds (interval length)

Environment:
dash 2.18.1
dash-mantine-components 0.14.5
dash-bootstrap-components 1.6.0

Thanks for your help!

1. Main code
```python
# app.py
import dash
from dash import dcc, html, _dash_renderer
import dash_bootstrap_components as dbc
import dash_mantine_components as dmc


_dash_renderer._set_react_version("18.2.0")
app = dash.Dash(__name__, use_pages=True, external_stylesheets=[dbc.themes.BOOTSTRAP])

navbar = dbc.NavbarSimple(
    dbc.DropdownMenu(
        [
            dbc.DropdownMenuItem(page["name"], href=page["path"])
            for page in dash.page_registry.values()
            if page["module"] != "pages.not_found_404"
        ],
        nav=True,
        label="More Pages",
    ),
    brand="Multi Page App Demo",
    color="primary",
    dark=True,
    className="mb-2",
)

app.layout = dmc.MantineProvider(
    dbc.Container(
        [
            navbar,
            dash.page_container,
            dcc.Interval(id="interval", interval=1000 * 10),
            dmc.NotificationProvider(limit=5),
            html.Div(id="notification-container"),
        ],
        fluid=True,
    )
)
if __name__ == "__main__":
    app.run(debug=True, port=8050)
```

2. Bar chart code with interval
```python
# bar_charts.py
import dash

dash.register_page(__name__)

from dash import Dash, dcc, html, Input, Output, callback
import dash_mantine_components as dmc
import plotly.express as px

df = px.data.tips()
days = df.day.unique()

layout = html.Div(
    [
        dcc.Dropdown(
            id="dropdown",
            options=[{"label": x, "value": x} for x in days],
            value=days[0],
            clearable=False,
        ),
        dcc.Graph(id="bar-chart"),
    ]
)


@callback(
    Output("bar-chart", "figure"),
    Output("notification-container", "children"),
    Input("dropdown", "value"),
    Input("interval", "n_intervals"),
    prevent_initial_call=True,
)
def update_bar_chart(day, n_intervals):
    ctx = dash.callback_context.triggered_id
    mask = df["day"] == day
    fig = px.bar(df[mask], x="sex", y="total_bill", color="smoker", barmode="group")
    return fig, dmc.Notification(
        title="Bar Chart Updated",
        message=f"Notification triggered by {day} selection and interval {n_intervals}, and context id {ctx}",
        autoClose=5000,
        action="show",
        style={"position": "fixed", "top": "20px", "right": "20px"},
    )
```

3. Another random page 
```python
# heat_maps.py
import dash

dash.register_page(__name__, path="/")

from dash import Dash, dcc, html, Input, Output, callback
import plotly.express as px

df = px.data.medals_wide(indexed=True)

layout = html.Div(
    [
        html.P("Medals included:"),
        dcc.Checklist(
            id="heatmaps-medals",
            options=[{"label": x, "value": x} for x in df.columns],
            value=df.columns.tolist(),
        ),
        dcc.Graph(id="heatmaps-graph"),
    ]
)


@callback(Output("heatmaps-graph", "figure"), Input("heatmaps-medals", "value"))
def filter_heatmap(cols):
    fig = px.imshow(df[cols])
    return fig
```

**Comment by Tomer-EVM** [comment]
Hi Ann Marie,
Thanks for your comment and good observation there.

When I said the notification was created without the callback firing I meant that the python debugger did not stop on a breakpoint on the first line of the callback. I also observe the print statements not being appended to the terminal when I'm not on the page. As you noted there is a dash error about callback Inputs being not in the layout which "stops" the execution of the callback.

So if the callback is not being fired, I don't understand why the notification continues to appear every 5 seconds on the other pages. The notification message is the same every time (i.e. the n_interval count does not increment). It also only begins to appear after the bar-charts page is visited for the first time, after which they continue indefinitely. To me it is unintuitive that the notifications continue to display even if the callback is not triggered. With this behaviour I don't know how to send the user relevant notifications for callbacks that are truly being executed on the page they are on if I have just a single interval driven callback in the entire app.

I appreciate your help and can continue the discussion in the plotly forum or dash issue tracker if you prefer.

```python
# bar_charts.py
@callback(
    Output("bar-chart", "figure"),
    Output("notification-container", "children"),
    Input("dropdown", "value"),
    Input("interval", "n_intervals"),
    State("url", "pathname"),
    prevent_initial_call=True,
)
def update_bar_chart(day: str, n_intervals: int, url: str):
    print("callback triggered")
    if url != "/bar-charts":
        return dash.no_update, dash.no_update # notification still shows even with early return

    ctx = dash.callback_context.triggered_id
    mask = df["day"] == day
    fig = px.bar(df[mask], x="sex", y="total_bill", color="smoker", barmode="group")
    return fig, dmc.Notification(
        title="Bar Chart Updated",
        message=f"Notification triggered by {day} selection and interval {n_intervals}, and context id {ctx}",
        autoClose=5000,
        action="show",
        style={"position": "fixed", "top": "20px", "right": "20px"},
    ```

**Comment by BSd3v** [comment]
You are more than likely encountering dash reloading the previous state of the app, which if you received a notification it never clears out.

Try using `set_props` and or the new `NotificationContainer`. Drop the output `bar-chart` and use the `set_props` instead.
