### ISSUE TITLE
MultiSelect auto-scroll behavior on Safari

### ISSUE THREAD

**Issue by mkmiller6** [snehilvj/dash-mantine-components#236]
On Safari (currently on version 17.2.1), adding an item to a MultiSelect or sometimes just selecting a MultiSelect causes the page to jump to the top.

Setting the MultiSelect to searchable prevents the issue from occuring.

I first noticed this behavior in my own app, but the same behavior can be seen on the [docs page](https://www.dash-mantine-components.com/components/multiselect) for the MultiSelect component.

The issue does not occur on Chrome as best I can tell.

Dash Mantine Components v0.12.1
Dash v2.16.1

**Comment by AnnMarieW** [comment]
I just tried this on Safari with V0.14.4 and could not duplicate this issue.  Closing for now.
