### ISSUE TITLE
RadioGroup not default Horizontal aligned

### ISSUE THREAD

**Issue by slyin87** [snehilvj/dash-mantine-components#239]
Hi,

In the documentation, the default is aligned horizontally..

https://www.dash-mantine-components.com/components/radiogroup

but now it is going downwards. How to make it go horizontally?

version 0.13.0a3

**Comment by slyin87** [comment]
TypeError: The `dash_mantine_components.RadioGroup` component (version 0.13.0a3) with the ID "chats_source_list" received an unexpected keyword argument: `orientation`

`Allowed arguments: aria-*, bg, bga, bgp, bgr, bgsz, bottom, c, children, className, classNames, data-*, description, descriptionProps, display, error, errorProps, ff, fs, fw, fz, h, id, inputWrapperOrder, inset, label, labelProps, left, lh, lts, m, mah, maw, mb, mih, miw, ml, mr, mt, mx, my, name, opacity, p, pb, persisted_props, persistence, persistence_type, pl, pos, pr, pt, px, py, required, right, size, style, styles, sx, ta, td, top, tt, unstyled, value, w, withAsterisk, wrapperProps`

**Comment by datenzauberai** [comment]
It seems to me to work as documented. You either wrap the Radio components in a Group (left to right) or in a Stack (top to bottom). @slyin87 could you try using a Group that wraps your Radio components?

**Comment by AnnMarieW** [comment]
Thanks for confirming @datenzauberai.
This also might  be an old issue since @slyin87 was running 13.0a3.
