### ISSUE TITLE
DateInput combo not styled

### ISSUE THREAD

**Issue by bufsim** [snehilvj/dash-mantine-components#242]
Hi,
I've upgraded  to the 0.14.0 and got this problem:

the date choice combo has no styling applied

<img width="1014" alt="image" src="https://github.com/snehilvj/dash-mantine-components/assets/30636385/648084ef-b18a-402b-b928-b469f485aace">

here is the code:

import dash
from dash import Dash, html
import dash_mantine_components as dmc  

app = dash.Dash()
dash._dash_renderer._set_react_version('18.2.0')
app = Dash(__name__)
app.layout = dmc.MantineProvider(withCssVariables=True,
children = html.Div([
    html.H1(children='DateInput', style={'textAlign':'center'}),
    dmc.DatesProvider(
        dmc.DateInput(id='f-data',label="DATA",
                             placeholder='AAAA/MM/GG',
                             clearable=True,
                             value='',
                             valueFormat="YYYY-MM-DD",), settings={'locale':'it'}), 
])
)
if __name__ == '__main__':
    app.run(host='0.0.0.0',debug=True)

**Comment by sysarchant** [comment]
suggested in discord:
`stylesheets = [
    "https://unpkg.com/@mantine/dates@7/styles.css",
    "https://unpkg.com/@mantine/code-highlight@7/styles.css",
    "https://unpkg.com/@mantine/charts@7/styles.css",
    "https://unpkg.com/@mantine/carousel@7/styles.css",
    "https://unpkg.com/@mantine/notifications@7/styles.css",
    "https://unpkg.com/@mantine/nprogress@7/styles.css",
]

app = Dash(__name__, external_stylesheets=stylesheets)`

**Comment by snehilvj** [comment]
Hi, I created a migration guide which you can refer to: https://www.dash-mantine-components.com/migration.
