### ISSUE TITLE
bug in version 0.14.0 with import DateRangePicker

### ISSUE THREAD

**Issue by alexeydg** [snehilvj/dash-mantine-components#244]
import dash_mantine_components as dmc
dmc.DateRangePicker

AttributeError: module 'dash_mantine_components' has no attribute 'DateRangePicker'. Did you mean: 'DateTimePicker'?

**Comment by system123** [comment]
I hit the same issue, the component you should use now is `DatePicker`, but I am then getting at `TypeError: r.useId is not a function` error.

**Comment by milosv-vtool** [comment]
Same problem as https://github.com/snehilvj/dash-mantine-components/issues/240, the workaround for now is to set environment variable `REACT_VERSION="18.2.0"` in `.env` file in the root of your folder.

**Comment by alexeydg** [comment]
> Same problem as #240, the workaround for now is to set environment variable `REACT_VERSION="18.2.0"` in `.env` file in the root of your folder.

it don't work

**Comment by milosv-vtool** [comment]
Can you provide a minimal reproduction, I tried this yesterday and it works fine, there are other issues since this is a breaking change in the original lib but the `r.useId` problem is no longer there.

**Comment by HWiese1980** [comment]
Has this been solved? I'm facing the same problem right now.

**Comment by AnnMarieW** [comment]
@HWiese1980 

Yes, this has been solved. 

 If you are getting the import error with `DateRangePicker`, use  `DatePickerInput(type="range")`
https://www.dash-mantine-components.com/components/datepickerinput#dates-range

If you are getting the `TypeError: r.useId is not a function` then either update Dash to >= 3.0.0 or set the React version to 18.2.0.  More info https://www.dash-mantine-components.com/getting-started
