### ISSUE TITLE
Burger lost in 0.14.0?

### ISSUE THREAD

**Issue by ihor-lazariev** [snehilvj/dash-mantine-components#247]
Is Burger not available anymore? 
I cannot see any changes to it at https://mantine.dev/changelog/7-0-0 and it is also still present on https://mantine.dev/core/burger/ for the latest version
```
import dash_mantine_components as dmc
burger = dmc.Burger()

AttributeError: module 'dash_mantine_components' has no attribute 'Burger'. 
```

**Comment by snehilvj** [comment]
Hi, yes Burger is missing for now, but will be added soon.

**Comment by snehilvj** [comment]
Burger had been added: https://www.dash-mantine-components.com/components/burger.
