### ISSUE TITLE
Enhancement Request: Automatic Disappearance of Tooltips After Hovering for a Specified Duration

### ISSUE THREAD

**Issue by andre996** [snehilvj/dash-mantine-components#248]
Feature Description:
Currently, the tooltip component offers various options for controlling its behavior, such as its position, offset, and visibility triggers. However, it lacks the ability to automatically hide after a specified duration of hovering over the target element.

Proposed Solution:
Introduce a new property, such as hover_duration, to the tooltip component. When this property is set, the tooltip should remain visible as long as the user hovers over the target element. After the specified duration elapses, the tooltip should automatically disappear.

Benefits:
Enhances user experience by providing a more intuitive behavior for tooltips.
Allows developers to easily control the duration for which tooltips remain visible during hovering.

**Comment by datenzauberai** [comment]
This is a good idea. However, keep in mind that DMC is just a thin wrapper around Mantine which does not seem to support this out of the box. I would suggest to request the enhancement in the upstream Mantine library.
