### ISSUE TITLE
DateInput does not use valueFormat setting

### ISSUE THREAD

**Issue by bufsim** [snehilvj/dash-mantine-components#249]
HI,
With the DateInput component, by setting valueFormat="DD/MM/YYYY" if I enter the date via keyboard it is not inserted according to the DD/MM/YYYY format. MM/DD/YYYY is entered. Everything is ok if I select the date with the combobox
for example if I write 09/26/1972 and press enter the field will write 02/01/2001. If I write 02/03/2020, in the field it says 03/02/2020
I wrote the same for DatePicker (https://github.com/snehilvj/dash-mantine-components/issues/131); it was a bug in Mantine v5 at the time, now I think Mantine v7 has the same bug, avoidable by using the dateParser prop to replace the default date parser.
is there a solution for dash mantine?

**Comment by Rykarix** [comment]
+1

Please implement dateParser as an argument of DateInput & other respective components
