### ISSUE TITLE
Inputs lacking readonly attribute

### ISSUE THREAD

**Issue by Haladesta** [snehilvj/dash-mantine-components#252]
There currently does not seem to be any way to add the readonly-attribute to inputs, i.e. `dmc.TextInput` and `dmc.NumberInput`.
_Dash-Boostrap-Components_' `dbc.Input` supports this as a [boolean parameter](https://dash-bootstrap-components.opensource.faculty.ai/docs/components/input/).

Since there also does not seem to be a method of adding it "manually", it'd be great to have it added similarly to the way boostrap does it.

**Comment by snehilvj** [comment]
Added readOnly prop. Will be available in next release.

**Comment by cheruvian** [comment]
Are there any workarounds here until that release drops and we have time to migrate?
