### ISSUE TITLE
Is there a component that adds row navigation to datatable

### ISSUE THREAD

**Issue by nat2k5us** [snehilvj/dash-mantine-components#253]
Is there a component that adds row navigation to datatable

i.e. using up/down arrow keys I want to be able to change the selection of a `row`

**Comment by snehilvj** [comment]
You can use actionicon?

**Comment by nat2k5us** [comment]
Can you elaborate - show an example

**Comment by AnnMarieW** [comment]
@nat2k5us 
I'm going to close this issue for now because it's stale and I'm not sure I understand the  question you are asking.  Feel free to re-open with more details an a minimal reproducible example.

**Comment by nat2k5us** [comment]
yes - please close it
