### ISSUE TITLE
AppShellHeader and AppShellMain overlaping

### ISSUE THREAD

**Issue by iBuitron** [snehilvj/dash-mantine-components#257]
Hi! 
Using this simple expample, when `header={"height": 60}` is not set, Header and Main overlaping, only when you set a header it works fine.
Is this a bug or works as it?
```py
dmc.AppShell(
    # header={"height": 60},
    children=[
        dmc.AppShellHeader("header"),
        dmc.AppShellMain([dmc.Text("some content", c="red")]),
    ]
)
```

**Comment by snehilvj** [comment]
If you are using Header in your app, you must specify its height.
