### ISSUE TITLE
Updating Notifications not working

### ISSUE THREAD

**Issue by rstol** [snehilvj/dash-mantine-components#258]
In version `0.14.3` the `Notification` `update` action prop is not working as expected. 

The update notification doesn't use the specified icon (keeps the loading icon) and doesn't automatically close. The `title`,  `message` and `color` do change correctly to the update Notification.   

This bug can be observed in [the Updating Notifications Docs](https://www.dash-mantine-components.com/components/notification). 

EDIT: This is not a bug. Apparently one needs to set `loading=False` and `autoClose` to some number to have the previous behavior. The correct usage is shown [here](https://mantine.dev/x/notifications/#update-notification)

**Comment by rstol** [comment]
Can you update the docs `docs/notification/update.py`? 

Thanks

**Comment by AnnMarieW** [comment]
Hi @rstol 
Thanks for reporting - this should be fixed now :slightly_smiling_face:
