### ISSUE TITLE
The dmc.ColorPicker doesn't show the color when it's value is updated

### ISSUE THREAD

**Issue by jincheeva** [snehilvj/dash-mantine-components#259]
The color picker works well when we pick a color. However, when we set the color value to the component, it doesn't display that color. Please use the following code to replicate the issue:

import dash_mantine_components as dmc
import dash_bootstrap_components as dbc
from dash import Dash, html, Input, Output, callback

app = Dash(__name__)

app.layout = html.Div(
    [
        dmc.ColorPicker(id="color-picker", format="hex"),
        dbc.Input(id="color-input", debounce=True),
    ]
)

@app.callback(
    Output("color-picker", "value"),
    Input("color-input", "value"),
)
def input_(color):
    return color

if __name__ == "__main__":
    app.run(debug=True)

**Comment by snehilvj** [comment]
Hi @jincheeva I can't reproduce the issue. Can you share a demo?

https://github.com/snehilvj/dash-mantine-components/assets/91216500/9936c39e-48ef-4e35-be89-dd97ab534f0f

**Comment by snehilvj** [comment]
Hi @jincheeva I can't reproduce the issue. Can you share a demo?

https://github.com/snehilvj/dash-mantine-components/assets/91216500/abb0bc64-fd7e-4353-855b-e201cce3e693

**Comment by jincheeva** [comment]
Thank you for your response. This is the video of the screen when we run the code below. We set the initial value of the colorpicker to be "#343353" but the colorpicker shows the white color in the upper left corner.
https://github.com/snehilvj/dash-mantine-components/assets/168907889/ee45d17e-a72d-45c3-b412-ed5359f3a4d2


import dash_mantine_components as dmc
from dash import Dash, Output, Input, html, callback

app = Dash()

app.layout = html.Div(
    [
        dmc.ColorPicker(id="color-picker", format="hex", value="#343353"),
        dmc.Space(h=10),
        dmc.Text(id="selected-color"),
    ]
)


@callback(Output("selected-color", "children"), Input("color-picker", "value"))
def pick(color):
    return color


if __name__ == "__main__":
    app.run(debug=True)

**Comment by snehilvj** [comment]
I don't face this issue in the latest version of dmc. Can you please confirm your version?

**Comment by jincheeva** [comment]
Thank you so much for your investigation and your reply. I was using version 0.12. After switching to version 0.14, I can confirm that the issue has been resolved. The colorpicker works well in version 0.14. Thank you so much.
