### ISSUE TITLE
No module named 'dash_mantine_components._imports_'

### ISSUE THREAD

**Issue by albavilanova** [snehilvj/dash-mantine-components#262]
Good morning,

I want to edit the code for version 0.12.1 of dash-mantine-components and test it locally to see if I can remove some errors in the DatePicker component. These are:

- Free input does not work with locale, it does not accept the date unless I write it in English.
- https://github.com/snehilvj/dash-mantine-components/issues/203

I will then install it using the setup.py file. The reason why I am not updating to 0.14 is because it the DatePicker does not seem to allow free input.

I got this error while testing:
```
import dash_mantine_components as dmc
File "/home/avilanov/anaconda3/envs/caliope-env/lib/python3.11/site-packages/dash_mantine_components/__init__.py", line 12, in <module>
    from ._imports_ import *
ModuleNotFoundError: No module named 'dash_mantine_components._imports_'
```

What are these imports? Is there a way to solve this?

Thank you,

Alba

**Comment by BSd3v** [comment]
Hello @albavilanova,

To use an input with DatePicker, you need to use DateInput.

https://www.dash-mantine-components.com/components/dateinput

**Comment by albavilanova** [comment]
Hi @BSd3v,

I've managed to get it to work using DateInput, thank you for the suggestion. The same errors still appear using the new version (#203 and the free input not accepting the values in the current locale). 

I want to test the master branch, but I tried installing the library in my environment and when I open my dashboard I keep encountering the imports error. I am doing:

```
git clone https://github.com/snehilvj/dash-mantine-components.git
python setup.py sdist
pip install dist/dash_mantine_components-0.14.3.tar.gz
```

Best,

Alba

**Comment by BSd3v** [comment]
Hello @albavilanova,

To build a local package, you need need to act like you are contributing as there is no dist package in the repo. To do so, you will need a need to have node installed.

Then run:
- `npm i` <- installs packages
- `npm run build` <- which will build the python library as well as the js
- `pip install -e .` <- will locally install the packages for you to test

Also, make sure that you run a `venv` as to not mess up your other packages.

**Comment by albavilanova** [comment]
I am closing this since I can now test it, I will open a new issue to report on the free input error.
