### ISSUE TITLE
Image components doesn't render data URIs

### ISSUE THREAD

**Issue by nuno-andre** [snehilvj/dash-mantine-components#267]
Data URIs (`data:image/jpeg;base64,{content}`) are not rendered by `dmc.Image` (which returns a `src="about:blank"`) or `dmc.Avatar` (which renders the default placeholder).

However, `html.Div` renders the same URI properly.

**Comment by AnnMarieW** [comment]
related to #256

**Comment by nuno-andre** [comment]
@AnnMarieW Thanks. I searched for "data URI/URL" and didn't find it. Closing as dupe.
