### ISSUE TITLE
Reducing package size by trimming metadata.json

### ISSUE THREAD

**Issue by aGitForEveryone** [snehilvj/dash-mantine-components#271]
When deploying python tools to cloud servers, package size is relevant to consider. When inspecting the package contents for dash mantine components (Linux version of the package, as the cloud runs on Linux), I see that the package is about 9MB. The major contributor to that is `metadata.json`. When opening I see that the file is constructed in nice format for humans, with a lot of indents. 

Is it possible to trim that, doing json.dumps with no indent specified? A small test on my system allowed me to reduce the size of the file by 2MB, which is about 20-25% size reduction.

**Comment by AnnMarieW** [comment]
Hi @aGitForEveryone 

Thanks for pointing this out - It looks like it will be possible to reduce the size of the metadata.json file and it will be in the next release. 🙂
