### ISSUE TITLE
Poor choice of font for code in docs 

### ISSUE THREAD

**Issue by ondave** [snehilvj/dash-mantine-components#275]
Thanks for this useful library, I just have a comment about the docs.

Maybe its just me, but I find it really hard to discriminate some of the upper/lowercase characters in the font used for the code snippets.

For example:
https://www.dash-mantine-components.com/components/button#full-width-button

![image](https://github.com/snehilvj/dash-mantine-components/assets/68404527/4600084a-f490-45e6-936a-5113490117b4)

Spent quite a while wondering why `fullwidth` wasn't working until I realised it was actually supposed to be `fullWidth`.

**Comment by deadkex** [comment]
![grafik](https://github.com/snehilvj/dash-mantine-components/assets/59506422/f644e1c3-743a-4270-88dd-b20c445456d3)
not sure why it looks like that for you

**Comment by ondave** [comment]
OK, interesting, maybe a font issue on my browser (ubuntu/Chrome). Not a big deal, just so you are aware.
