### ISSUE TITLE
dmc.Accordion styles for active item do not work in 0.14

### ISSUE THREAD

**Issue by arnavdoss-vo** [snehilvj/dash-mantine-components#276]
Since the update to 0.14, the dmc.Accordian styles for item -> &[data-active] no longer work. Nothing inside the &[data-active] works anymore. Example of usage is shown below.

`dmc.Accordion(
            id="accordian",
            styles={
                "item": {
                    "border": "2px solid transparent",
                    "&[data-active]": {
                        "border": "2px solid green",
                    },
                },
            },
        )`

**Comment by zndr27** [comment]
dmc.Accordion are not displaying for me at all

**Comment by AnnMarieW** [comment]
I'm not sure why the `styles` prop isn't working, but here is a workaround just using regular `className` prop

put the following in a .css file in the assets folder:

```

.dmc-active[data-active] {
  color: red;
}


```



```python
import dash_mantine_components as dmc
from dash import Dash, _dash_renderer

_dash_renderer._set_react_version("18.2.0")

app = Dash(__name__, external_stylesheets=dmc.styles.ALL)

accordion = dmc.Accordion(
    children=[
        dmc.AccordionItem(
            [
                dmc.AccordionControl(
                    "Personal Information",
                    className="dmc-active",
                ),
                dmc.AccordionPanel("some content"),
            ],
            value="info",
        ),
        dmc.AccordionItem(
            [
                dmc.AccordionControl(
                    "Shipping Address",
                    className="dmc-active",
                ),
                dmc.AccordionPanel("some content"),
            ],
            value="addr",
        ),
        dmc.AccordionItem(
            [
                dmc.AccordionControl(
                    "Confirmation",
                    className="dmc-active",
                ),
                dmc.AccordionPanel("some content"),
            ],
            value="focus",
        ),
    ],
)

app.layout = dmc.MantineProvider(
    [
        accordion,
    ]
)

if __name__ == "__main__":
    app.run(debug=True)


```

![image](https://github.com/user-attachments/assets/9c0f7cb9-975b-41f5-84ce-c39e4ef9a803)

**Comment by AnnMarieW** [comment]
dmc 0.14 wraps Mantine 7.  As of Mantine 7, the `styles` prop no longer supports nested selectors, and the recommended method is to use a style sheet and `className`  as described above.

More info in the Mantine changelog:  https://github.com/mantinedev/mantine/releases/tag/7.0.0
