### ISSUE TITLE
Lag caused by dmc.Select with many options (~20k)

### ISSUE THREAD

**Issue by RainyBlue-w** [snehilvj/dash-mantine-components#279]
Hello! I'm using 'dmc.Select' for selecting a gene from a large genes list(~20k). When I set the 'data' props as this large list, the page get stuck. However, things doesn't happen when I use dcc.Dropdown instead. So I'm wondering if there is some thing different between them that caused this problem.

**Comment by rudibroekhuizen** [comment]
I have the same issue when using dmc.MultiSelect. When using dcc.Dropdown using the same data, the page works fine. When using dmc.MultiSelect, performance is degraded.

**Comment by deadkex** [comment]
Try setting both these options in the select
`searchable=True` https://www.dash-mantine-components.com/components/select#searchable
`limit=100` https://mantine.dev/core/select/#large-data-sets

**Comment by rudibroekhuizen** [comment]
That works for me, thanks.
