### ISSUE TITLE
Components are not rendering if dash.app(debug=False) used

### ISSUE THREAD

**Issue by ihor-lazariev** [snehilvj/dash-mantine-components#287]
dash_mantine_components==0.14.3

MRE:
```
import os

import dash_bootstrap_components as dbc
import dash_mantine_components as dmc
from dash import Dash, html

# for dash_mantine_components
os.environ["REACT_VERSION"] = "18.2.0"

app = Dash(__name__)

app.layout = dmc.MantineProvider(
    children=[
        html.P("Test"),
        html.Button("HTML Button"),
        dbc.Button("DBC Button"),
        dmc.Button("DMC Button No Anchor"),
        dmc.Anchor(dmc.Button("DMC Button Anchor"), href="/logout"),
    ],
)

if __name__ == "__main__":
    app.run(debug=False)
```
**Expected (debug=True):**
<img width="588" alt="Screenshot 2024-07-30 at 23 39 49" src="https://github.com/user-attachments/assets/5ad72cc5-48f4-4217-9d0d-847da1ed34f7">

**Actual (debug=False):**
<img width="330" alt="Screenshot 2024-07-30 at 23 36 53" src="https://github.com/user-attachments/assets/875f6644-2fff-41ae-aa22-c4fba4b22bd7">

**Comment by AnnMarieW** [comment]
Hi @ihor-lazariev 

I just ran your example, and couldn't reproduce the issue.  For me, it worked fine with both debug=True or False.

Do you get any errors in the console when the debug is False?  What system are you using? Which browser?

**Comment by ihor-lazariev** [comment]
> Do you get any errors in the console when the debug is False?

<img width="555" alt="Screenshot 2024-07-31 at 00 32 54" src="https://github.com/user-attachments/assets/71dc02b4-9308-45f6-bea2-384e4bbca47b">


> What system are you using? 

MacOS Sonoma/Windows 11, python 3.11.9


> Which browser?

Safari/Chrome latest


it seems there are some conflicting packages from project venv. I'll try to find one

**Comment by AnnMarieW** [comment]
From that image, it looks like it's using React 16

Try setting it with 
```
dash._dash_renderer._set_react_version('18.2.0')
```

Solution from @koala on the dmc Discorde :slightly_smiling_face:

**Comment by ihor-lazariev** [comment]
> From that image, it looks like it's using React 16
> 
> Try setting it with
> 
> ```
> dash._dash_renderer._set_react_version('18.2.0')
> ```
> 
> Solution from @Koala on the dmc Discord 🙂

Strange that os.environ not working here, but the fix is fine
Big thanks! :)
