### ISSUE TITLE
DateInput doesn't 'closeOnEscape' (popover prop)  - with workaround

### ISSUE THREAD

**Issue by Rykarix** [snehilvj/dash-mantine-components#288]
```python 
dmc.DateInput(
    id="date-input-start",
    label="Start Date",
    valueFormat="DD/MM/YYYY",
    value=datetime.now(tz=timezone.utc),
    persistence=False,
    popoverProps={
        "closeOnEscape": True, # This should be Default behavior. Bugged?
    },
),
```
Note 1: Might be related to https://github.com/mantinedev/mantine/issues/2827 (different element but probably similar logic related to focus if you read comments)
Note 2: Also affects main website: https://www.dash-mantine-components.com/components/dateinput

For those that want a fix, I wrote something quick:

make this file: `assets/keybinds.js`
```javascript
document.addEventListener('keydown', function(event) {
    if (event.key === "Escape") {
        var dateInputs = document.querySelectorAll('.mantine-DateInput-input');
        dateInputs.forEach(function(input) {
            if (input === document.activeElement) {
                input.blur();
            }
        });
    }
});
```

**Comment by AnnMarieW** [comment]
Hi @Rykarix 
Thanks for reporting this issue, I see the same behavior in Mantine, so it will have to be fixed there..  

Your workaround is great and will be the recommended solution for now.
