### ISSUE TITLE
withinPortal breaks NotificationProvider position

### ISSUE THREAD

**Issue by iBuitron** [snehilvj/dash-mantine-components#289]
When use withinPortal=False (Cuz notification is inside a Modal)

```
dmc.NotificationProvider(
            position="top-center",
            withinPortal=False,
)
```

it breaks position and have to use custom styles like:
```
dmc.NotificationProvider(
            # position="top-center",
            withinPortal=False,
            style={
                "position": "absolute",
                "top": 20,
                "left": "50%",
                "transform": "translateX(-50%)",
            }
```

There any way to fix that?

**Comment by AnnMarieW** [comment]
Hi @iBuitron 

This may be related to https://github.com/snehilvj/dash-mantine-components/issues/290
Can you try updating to 0.14.4 and check out the new [Getting Started](https://www.dash-mantine-components.com/getting-started) section?

**Comment by iBuitron** [comment]
Hi @AnnMarieW, thx! it works.

Setting `dmc.styles.NOTIFICATIONS` on `external_stylesheets` fix that.
