### ISSUE TITLE
[Feature Request] Add "active" prop to  DMC Carousel

### ISSUE THREAD

**Issue by philipp-leibner** [snehilvj/dash-mantine-components#292]
Hi,

I would like to implement a Mantine Carousel using DMC. However I could net find any attribute that lets me the set active slide using some logic or callback. I would like the carousel to alternate between two slide every couple of seconds. Is there any way to achieve this behavior?

**Comment by AnnMarieW** [comment]
Hi @philipp-leibner 


It appears that there is no "active" slide prop, but you can control which slide is displayed using the `initialSlide` prop.  Try this example:

```python

import dash_mantine_components as dmc
from dash import Dash, _dash_renderer, dcc, Input, Output
_dash_renderer._set_react_version("18.2.0")

app = Dash(external_stylesheets=dmc.styles.ALL)

def make_slide(text):
    return dmc.Card(
        dmc.Text(f"Slide {text}"),
        withBorder=True,
        shadow="sm",
        radius="md",
        bg="green",
        c="white",
        m=50
    )

app.layout = dmc.MantineProvider([
    dcc.Interval(id="interval", interval=2000, n_intervals=0 ),
    dmc.Carousel([
        dmc.CarouselSlide(make_slide(1)),
        dmc.CarouselSlide(make_slide(2)),
    ],
        id="carousel"
    )
])

@app.callback(
    Output("carousel", "initialSlide"),
    Input("interval", "n_intervals")
)
def update(n):
    if n % 2 ==0:
        return 0
    return 1

if __name__ == "__main__":
    app.run(debug=True)

```

**Comment by philipp-leibner** [comment]
Thank you!

**Comment by AnnMarieW** [comment]
@philipp-leibner   In the next release there will also be an autoplay prop - and that will probably work even better for your use case #316 :tada:
