### ISSUE TITLE
Carousel's don't work in Tabs (except first tab)

### ISSUE THREAD

**Issue by michaelrussell4** [snehilvj/dash-mantine-components#299]
Carousel slide content doesn't update when pressing right/left if the `dmc.Carousel` is in a `dmc.TabsTab` and is not the first `dmc.TabsTab` of the `dmc.TabsList`. This is very odd because it works fine if it's the first tab but for any other than the first tab the carousel slide content won't update _unless_ you press F12 and open your dev window—if you do this then the slide content suddenly updates to reflect the slide content corresponding with the indicator slide number.

Here's an example. You'll see that the carousel in the first tab (the "Gallery" tab) works, while the others don't. 
dash_mantine_components==0.14.4
```py
import dash
from dash import _dash_renderer
import dash_mantine_components as dmc

_dash_renderer._set_react_version("18.2.0")
app = dash.Dash(__name__, external_stylesheets=[dmc.styles.CAROUSEL])

carousel = dmc.Carousel(
    loop=True,
    withIndicators=True,
    children=[
        dmc.CarouselSlide(
            dmc.Center(
                "Slide 1",
                bg="blue",
                c="white",
                p=30,
            )
        ),
        dmc.CarouselSlide(
            dmc.Center(
                "Slide 2",
                bg="green",
                c="white",
                p=30,
            )
        ),
        dmc.CarouselSlide(
            dmc.Center(
                "Slide 3",
                bg="orange",
                c="white",
                p=30,
            )
        ),
    ],
    id="carousel-simple",
)

tabs = dmc.Tabs(
    [
        dmc.TabsList(
            [
                dmc.TabsTab("Gallery", value="gallery"),
                dmc.TabsTab("Messages", value="messages"),
                dmc.TabsTab("Settings", value="settings"),
            ]
        ),
        dmc.TabsPanel(carousel, value="gallery"),
        dmc.TabsPanel(carousel, value="messages"),
        dmc.TabsPanel(carousel, value="settings"),
    ],
    value="gallery",
)

app.layout = dmc.MantineProvider(tabs)

if __name__ == "__main__":
    app.run_server(debug=True)
```

https://github.com/user-attachments/assets/d612ac8a-0e0f-4acd-85a3-945088571971

**Comment by AnnMarieW** [comment]
Hi @michaelrussell4 

Thanks for reporting.  It looks like this is a bug in the upstream Mantine library https://github.com/orgs/mantinedev/discussions/4887

**Comment by jmanali1996** [comment]
Thank you so much for sharing the solution. I replaced the dmc.TabsPanel with the callback and the carousel is working smoothly!

**Comment by AnnMarieW** [comment]
The docs have now been updated to note this limitation.  I'll close this for now since it's an issue in the upstream Mantine library.
