### ISSUE TITLE
`dmc.Collapse` - required parameter `in` does not work

### ISSUE THREAD

**Issue by MichaelODeli** [snehilvj/dash-mantine-components#305]
When I try to use the undocumented [Collapse](https://mantine.dev/core/collapse/) component, I get the following error:
```python
    dmc.Collapse(in=True, children=[dmc.Button()])
                 ^^
SyntaxError: invalid syntax
```
Same issue with [Fieldset](https://mantine.dev/core/fieldset/) and [NumberFormatter](https://mantine.dev/core/number-formatter/) (undocumented props).

---
I also saw that the following components are missing: [Tree](https://mantine.dev/core/tree/), [SemiCircleProgress](https://mantine.dev/core/semi-circle-progress/), [Dialog](https://mantine.dev/core/dialog/), [ColorSwatch](https://mantine.dev/core/color-swatch/),

**Comment by AnnMarieW** [comment]
Hi @MichaelODeli 
Thanks for reporting - I could replicate this issue with the `in` prop.

Are you interested in doing any pull requests either in the dmc-doc repo or here?

**Comment by MichaelODeli** [comment]
@AnnMarieW Yes, I will try to add undocumented components to dmc-docs.

**Comment by MichaelODeli** [comment]
The same error with Fieldset components - unexpected argument
```
TypeError: The `dash_mantine_components.Fieldset` component (version 0.14.4) received an unexpected keyword argument: `disabled`
```
But in dmc-docs with `configurator.add_switch("disabled", False)` param - it works fine

**Comment by AnnMarieW** [comment]
That's odd - but in the upstream docs, `disabled` is not a valid prop for `Fieldset`
https://mantine.dev/core/fieldset/?t=props

**Comment by AnnMarieW** [comment]
I think I see how to fix this.  It would be helpful if you could make a draft PR for the Fieldset component, then when the fix is done, the docs will be ready to go.  :-)

**Comment by MichaelODeli** [comment]
@AnnMarieW https://github.com/snehilvj/dmc-docs/pull/64

**Comment by alexcjohnson** [comment]
FWIW there _is_ a way to use props masked by Python keywords, or that in some other way are invalid as kwargs:

```py
dmc.Collapse(children=[dmc.Button()], **{"in": True})
```

Which is what you have to do for example to use the [`data-*` and `aria-*` wildcard props in `dash.html`](https://github.com/plotly/dash/pull/237) because of the hyphens.

But I agree, this pattern is tricky, ugly, and non-Pythonic so better to change it where we can.
