### ISSUE TITLE
 module 'dash_mantine_components' has no attribute 'styles'

### ISSUE THREAD

**Issue by kevingeother** [snehilvj/dash-mantine-components#315]
I am trying to add the external stylesheets for the Carousel 

` app = Dash(external_stylesheets=dmc.styles.ALL)`

but I get the error that  module 'dash_mantine_components' has no attribute 'styles'. 

I am on version 0.14.3

**Comment by AnnMarieW** [comment]
Hi @kevingeother 

If you  upgrade to 0.14.4 it will fix the error :slightly_smiling_face:
