### ISSUE TITLE
DatePicker does not hold selected value, displays one day prior to selection

### ISSUE THREAD

**Issue by rick643charts** [snehilvj/dash-mantine-components#33]
The DatePicker component appears to not hold the selected value after losing focus. It seems to select one day prior to the selected value. This issue can be replicated in the first example [here](https://dash-mantine-components.herokuapp.com/components/datepicker) by attempting to select February 3, 2022. After losing focus, the underneath text will show the correct selected value, however the display value in the DatePicker component will display February 2, 2022.

As a heavy user of the Dash Bootstrap Components library, these components are a great supplement, thank you for your work!

**Comment by snehilvj** [comment]
Hi @rick643charts thanks for your interest in dmc.
I don't see any unusual behaviour in the DatePicker on the docs. Here are some things I tried:
https://user-images.githubusercontent.com/91216500/152109556-889b70f0-5be8-424e-86a0-a8623fd6eec6.mov
Did I miss anything?

**Comment by rick643charts** [comment]
Appreciate the quick reply. That's very odd that it's behaving differently on my end, yours looks correct. See below:

https://user-images.githubusercontent.com/76791595/152110821-e25c78a2-bade-4970-a0b7-d7c2d53c361f.mp4

**Comment by snehilvj** [comment]
hmmm weird. I'll have a look at this. Thanks for reporting.

**Comment by rick643charts** [comment]
Did some additional testing in Chrome, as well as Chrome incognito browser, and issue still persists. Tested in Microsoft Edge and issue is reproducible there too.

**Comment by rick643charts** [comment]
Any progress on identifying the root cause of these behavior? Appreciate your support and continued development on this project!

**Comment by emilhe** [comment]
@rick643charts What time zone are you in? What browser are you using?

**Comment by rick643charts** [comment]
PST, experiencing the same behavior in both Chrome and Microsoft Edge. No errors being written to the JS console it appears. The backend value appears to be correct, just the displayed value is incorrect (e.g. selecting 2022-03-13 will propagate correctly in the relevant callbacks, but the display value in the component will be 2022-03-12).

**Comment by kaburelabs** [comment]
@rick643charts It's already fixed an will be live in the next update

**Comment by snehilvj** [comment]
The issue has been fixed.

**Comment by snehilvj** [comment]
@rick643charts Just released 0.6.0 version of dmc, which includes the fix for datepicker not working properly in certain timezones. Can you please check [here](https://dash-mantine-components.herokuapp.com/components/datepicker) if its alright now?

**Comment by rick643charts** [comment]
Confirmed it's functioning properly on my end now, thanks for the resolution here!
