### ISSUE TITLE
Animation property is not working in Line Chart

### ISSUE THREAD

**Issue by namakshenas** [snehilvj/dash-mantine-components#330]
Tried the following piece of code:

```
data = [
    {"date": "Mar 22", "Apples": 2890, "Oranges": 2338, "Tomatoes": 2452},
    {"date": "Mar 23", "Apples": 2756, "Oranges": 2103, "Tomatoes": 2402},
    {"date": "Mar 24", "Apples": 3322, "Oranges": 986, "Tomatoes": 1821},
    {"date": "Mar 25", "Apples": 3470, "Oranges": 2108, "Tomatoes": 2809},
    {"date": "Mar 26", "Apples": 3129, "Oranges": 1726, "Tomatoes": 2290}
]

html.Div(
        dmc.LineChart(
            h=300,
            dataKey="date",
            data=data,
            tooltipAnimationDuration=500,
            lineChartProps={"isAnimationActive":True,  
                            "animationDuration": 500, 
                            "animationEasing": "ease-in-out",
                            "animationBegin": 500},
            series=[
                {"name": "Apples", "color": "indigo.6"},
                {"name": "Oranges", "color": "blue.6"},
                {"name": "Tomatoes", "color": "teal.6"},
            ],
        )
```

But the chart loaded without any animation!

**Comment by AnnMarieW** [comment]
Hi @namakshenas 
Thanks for reporting!
It's not working because the animation needs to be set using the `lineProps` property, which is missing.  This prop will be added in the next release.

**Comment by namakshenas** [comment]
> Hi @namakshenas
> 
> Check out this [sample app hosted on PyCafe](https://py.cafe/snippet/dash/v1#c=H4sIAEw3CWcAA6VWbY_aOBD-K5Y_gZSEvMCyRIrU3bbSnW6rnk69uw-bVWSSgbgNduo4bCPEf-84L9AC-6I2IJJx5plnxn48ZkdTmQENaSxWSm6IYiLDG9-UUunW4kLHorczVuXJhgnNBSSpxEEBQleEVSTbpH0I4zQEeIfPFklanAKRgQJlkZQVxZKlXyzypyhrbZGPtcZ7LH52dJIKNFos1ckWVMWlGMXUu3Z8x43pOBaxYGVJopZlBN80KMGKpNJNAVUOoKsIs3I627m5u2shac4wscgk7NxhHW-NPYoFwYtnUUwLHGydbIZ1M420MbU6hzwKXLd_zphmf0GDCHyCg4sZju53-4fe1lIWmpc3Q6x3tWrv0ewQyTD-rWRZRbuY8urgepNqvsXI4SdVQ-97esX0kOUQGQHkGPwZwHtWcbE27jEFVoHNhS1xHYZSnoHewpoPRPvevQLFoYruj2AsR7CNqQCxN2WJ64DB8TmVhVTdMEeJraVzFdMhzhnyI-pwfQG6LGp4FvhJYrbyAlIDK35EmsVq1dFKyilYg_PQi-RDp3dcoC1HXY76-syr21rrVpT_lkYDpNWSIWuFtNTCviimcc_avojFQ8v8ZtgVvRa7PYGxL-sRizBKOwZrtxK6P8lqICJJC55-wQlBTvxmsCJ1m_tIjMMukAJdK0H6MnE-O3mbafvAFPH9LtSwnCHxrxeuGTksEw4FwbUZOi5AODSTkeeiNskUf8fD9J-TBGck89nVKYnnBr9FMj0lCQLfPyFZXLe0v8wxO-OYzs9my3N_b7ZQyScknr84IfHm_qsqQT12G4GvSJKYvZQkJIoQmWDr5yJJENklYraKqsUog2W9jkyTGlOLKvhacwUbczLgwWJaOgrtiZPjDcm1LqtwMikbJ2UrmKzzCQqXr7DrTyoBOS-2nycGbvdw-wif-O50NncXi7nbulxgsF3Hmzozu2wCW-AQ7ojGecwLTFQ3pTn5DBAtLOY_Do80XLGiAotCxvV7wZYF-mjTf2nZ6FwKRJSNzLAV2FvX8a8cD8Fdw6DhjvYHFQ19nAkp9T8SQ-4GLoWWRVMsKsNTjob3hzeaLfG0w5ePPNM5Db2Za9ENF_93ZtBZfwBf58hjTJ4hbMULuMWo2HvfSqFxfUA9wWBc7WXniy4lM3Ep3T_srfMsnkjxiDNrXzY_o19R3csV9Rm-VM1QyOX08z6qN5-9hhP_OeAwK14iHfwMq_nsrXZWUeb3D_vv2w3ucksJAAA) based on the PR

Briliant!

Btw, do you have any plan to add the animation to different chart types?

**Comment by AnnMarieW** [comment]
yes - working on it right now as part of this same PR.  It works for some charts already, like the pie and donut.  Just adding the other missing props for the others :-)

**Comment by namakshenas** [comment]
> yes - working on it right now as part of this same PR. It works for some charts already, like the pie and donut. Just adding the other missing props for the others :-)
> 
> @namakshenas it should work with the bar charts, it's just not documented. Just use the `barProps` rather than `barChartProps`

Well done! Looking forward to it!
