### ISSUE TITLE
DatimeTimePicker rendering issue

### ISSUE THREAD

**Issue by sssaha** [snehilvj/dash-mantine-components#331]
Hello 
I am trying to use the DateTimePicker object in the latest version and it seems like if the component is part of a DMC drawer or a children of an Accordion component - it does not render properly.  

![image](https://github.com/user-attachments/assets/85772f45-6245-4f25-ae80-dca9d7e715a4)

This is how I am defining the DateTImePicker 

```
dmc.DateTimePicker(label='Recording End Time', id=f'{cls.selected_test}_stop_time_datetime',
                                                                                              value=datetime.now(),valueFormat="MM/DD/YYYY HH:mm:ss",
                                                                                              withSeconds=True,popoverProps={'zindex': 10000})
```

where the drawer component has a zinder of 5000. 
Am I doing something wrong?

**Comment by AnnMarieW** [comment]
Hi @sssaha 
Be sure to include the additional stylesheets
See the getting started section for more info  - https://www.dash-mantine-components.com/getting-started

```
https://www.dash-mantine-components.com/getting-started
```

**Comment by sssaha** [comment]
I did - but I think I found what is the issue. I use both the bootstrap and dmc styles, dmc styles.ALL is a list where everything else is just the stylesheet itself. So I had external stylesheet like this - external_stylesheets=[dbc.themes.BOOTSTRAP,dmc.styles.ALL] - which is wrong. It was an issue on my end.

**Comment by AnnMarieW** [comment]
Glad you solved the problem :tada: 

It's noted in the Getting Started Section as well:

![image](https://github.com/user-attachments/assets/0a44df91-95ed-4de1-ba85-db36ec201b8d)

**Comment by sssaha** [comment]
@AnnMarieW 
So now the rendering is fine in terms of component. However see the screenshot - where the popover is behind the drawer - even through the drawer has a lower z index than the popover as I set via the popoverProps={'zindex': 1000000}

![image](https://github.com/user-attachments/assets/5fad5dad-66f4-4ede-a68b-e8b8968755d2)

**Comment by AnnMarieW** [comment]
Hi @sssaha 
Can you make a complete minimal example that reproduces the issue?

**Comment by sssaha** [comment]
Please close this ticket. I found the issue. In the popovertargets parameter of the date time picker I had dict(zindex=300000), which should be dict(zIndex=300000)

**Comment by sssaha** [comment]
Thanks for your help
