### ISSUE TITLE
[Feature Request] Allow Multiselect to trigger callbacks on dropdown close.

### ISSUE THREAD

**Issue by snehilvj** [snehilvj/dash-mantine-components#34]
As suggested in [forum](https://community.plotly.com/t/multi-select-dropdown-that-doesnt-run-callback-until-all-choices-selected/60613),
Adding a `dropdownClosed` prop will enable triggering callbacks after a user is done selecting all the desired values.

**Comment by Lxstr** [comment]
@snehilvj Hi there. I'd be interested to help implement this!

**Comment by AnnMarieW** [comment]
Rather than adding another prop like `dropdownCose` it would be better to handle this with `debounce=True`

Check out this example based on  PR #383

https://py.cafe/amward/dmc-pr-383-demo-multi-select

**Comment by Lxstr** [comment]
Amazing work!
