### ISSUE TITLE
DateRangePicker modal does not render inside of bootstrap offcanvas

### ISSUE THREAD

**Issue by MartinHanewald** [snehilvj/dash-mantine-components#35]
Hi there, thank you for your great work! This library is a very valuable extension to the dash ecosystem.

I have to report an issue with the DateRangePicker component. The picker popup does not render when inside an offcanvas sidebar from the dash bootstrap components. I have no idea about what the problem might be here. I drew up a minimal reproducible example

```python
import dash
import dash_bootstrap_components as dbc
import dash_mantine_components as dmc
import flask
from dash import dcc, html
from dash.dependencies import Input, Output, State

server = flask.Flask("app")
server.secret_key = "LOREM IPSUM"

app = dash.Dash("app", server=server, external_stylesheets=[dbc.themes.BOOTSTRAP])

app.layout = dbc.Container(
    dbc.Row(
        dbc.Col(
            [
                html.H1("Issue with Offcanvas"),
                # THIS ONE WORKS
                dmc.DateRangePicker(id="picker_outside"),
                dbc.Button("Open Offcanvas", id="toggle"),
                dbc.Offcanvas(
                    [
                        html.Div(
                            [
                                html.H1("Offcanvas Content"),
                                # THIS ONE DOESN'T WORK
                                dmc.DateRangePicker(id="picker_inside"),
                            ]
                        )
                    ],
                    id="offcanvas",
                    is_open=False,
                    placement="end",
                ),
            ],
        )
    ),
    className="container",
)


@app.callback(
    Output("offcanvas", "is_open"),
    Input("toggle", "n_clicks"),
    State("offcanvas", "is_open"),
)
def toggle_offcanvas(n, is_open):
    if n:
        return not is_open
    return is_open


if __name__ == "__main__":
    app.run_server(debug=True)

```

**Comment by MartinHanewald** [comment]
![offcanvas issue](https://user-images.githubusercontent.com/31796919/152132259-afe23199-6e31-4fe6-93cf-3c47a9d1de05.gif)

**Comment by snehilvj** [comment]
Hi @MartinHanewald 
Thanks for your interest in dmc and drawing up this MRE. This behaviour is because of zIndex values of the Offcanvas and the DateRangePicker. The date range picker is actually popping up but behind the Offcanvas. To mitigate this, just set the zIndex value of date range picker to be higher than Offcanvas.
```python
html.H1("Offcanvas Content"),
# THIS ONE DOESN'T WORK
dmc.DateRangePicker(id="picker_inside", zIndex=1050),
```
Thanks for bringing this into my notice, I'll try to create a section in the docs dedicated for things like these.

**Comment by MartinHanewald** [comment]
Jeez, that was actually my first intuition! I tried around with setting different zIndexes via CSS, but apparently I did not catch the right selector. I did not see the parameter of the class itself. Thanks a bunch, for that quick response!
