### ISSUE TITLE
Unit display in yAxis labels, extra lines at the left and right, and yAxis labels in the right of vertical BarChart

### ISSUE THREAD

**Issue by namakshenas** [snehilvj/dash-mantine-components#362]
Hi,

Here is my dataset, I'm trying to create a bar chart:

```
data = [
    {"dmu": "dmu1", "Efficiency score": 100},
    {"dmu": "dmu2", "Efficiency score": 78},
    {"dmu": "dmu3", "Efficiency score": 100},
    {"dmu": "dmu4", "Efficiency score": 100},
    {"dmu": "dmu5", "Efficiency score": 89},
    {"dmu": "dmu6", "Efficiency score": 95 }
]
```

and this is the code via DMC, which produces the bar chart:

```
html.Div(
    [
        dmc.BarChart(
            h=400,
            dataKey="dmu",
            data=data,
            xAxisProps={"padding": {"left": 5, "right": 5}},
            yAxisProps={"padding": {"top": 30, "buttom": 30}},
            gridAxis='y',
            tickLine=None,
            withLegend=True,
            unit="%",
            barProps={
                "radius": 5,
                "isAnimationActive": True,
            },
            orientation="vertical",
            series=[
                {"name": "Efficiency score"},
            ],
        )
    ],
)
```

And here is the snapshot of the chart:

<img width="1397" alt="Screenshot 2024-10-17 at 11 31 25" src="https://github.com/user-attachments/assets/bc4cfe59-6c49-406b-854b-9f1dcbd88259">

**Issue 1.** The units should not be shown in the yAxis labels.
**Issue 2.** There are extra lines at the rightmost and leftmost of the chart.
**Issue 3.** The yAxis labels on the right side should not be shown.

**Comment by AnnMarieW** [comment]
Hi @namakshenas 

Same comment as in #363:


>If you create the same chart in Mantine, do you get the same results?  Since dmc is just a wrapper around Mantine, need to figure out if this is a dmc bug or not.

**Comment by namakshenas** [comment]
Hi @AnnMarieW,

Here is the working example in `@mantine/charts`:

```
<BarChart
          h={300}
          data={[
            { dmu: 'dmu1', 'Efficiency score': 100, Status: 'Efficient', color: '#32CD32' },
            { dmu: 'dmu2', 'Efficiency score': 78, Status: 'InEfficient', color: '#FFA500' },
            { dmu: 'dmu3', 'Efficiency score': 100, Status: 'Efficient', color: '#32CD32' },
            { dmu: 'dmu4', 'Efficiency score': 100, Status: 'Efficient', color: '#32CD32' },
            { dmu: 'dmu5', 'Efficiency score': 89, Status: 'InEfficient', color: '#FFA500' },
            { dmu: 'dmu6', 'Efficiency score': 95, Status: 'InEfficient', color: '#FFA500' },
          ]}
          withBarValueLabel
          orientation="vertical"
          gridAxis="y"
          barProps={{ radius: 5 }}
          dataKey="dmu"
          series={[{ name: 'Efficiency score' }]}
          tickLine="none"
/>
```

And this is the snapshot of the chart:

<img width="1151" alt="Screenshot 2024-10-17 at 16 08 52" src="https://github.com/user-attachments/assets/4fe8bffc-0a80-46ed-bd3d-8d3dbd6e1532">

So:
**Issue 1.** (I believe this can be achieved by manipulating the tooltip, so forget about this)
**Issue 2.** In `@mantine/charts`, there are no extra lines.
**Issue 3.** In `@mantine/charts`, the yAxis labels are not shown on the right side.

**Comment by AnnMarieW** [comment]
Be sure you are on the latest release, 0.14.6 and with the same props as you provided, I see the same figure you posted

```
import dash_mantine_components as dmc
from dash import Dash, _dash_renderer, html
_dash_renderer._set_react_version("18.2.0")

app = Dash(external_stylesheets=dmc.styles.ALL)

component = dmc.BarChart(
    h=300,
    data=[
        {"dmu": "dmu1", "Efficiency score": 100, "Status": "Efficient", "color": "#32CD32"},
        {"dmu": "dmu2", "Efficiency score": 78, "Status": "InEfficient", "color": "#FFA500"},
        {"dmu": "dmu3", "Efficiency score": 100, "Status": "Efficient", "color": "#32CD32"},
        {"dmu": "dmu4", "Efficiency score": 100, "Status": "Efficient", "color": "#32CD32"},
        {"dmu": "dmu5", "Efficiency score": 89, "Status": "InEfficient", "color": "#FFA500"},
        {"dmu": "dmu6", "Efficiency score": 95, "Status": "InEfficient", "color": "#FFA500"},
    ],
    withBarValueLabel=True,
    orientation="vertical",
    gridAxis="y",
    barProps={"radius": 5},
    dataKey="dmu",
    series=[{"name": "Efficiency score"}],
    tickLine="none",
)

app.layout = dmc.MantineProvider(
    component
)

if __name__ == "__main__":
    app.run(debug=True)
```

**Comment by namakshenas** [comment]
Just updated to 0.14.6. Issue 3 is now gone. But, issue 2 (extra lines) still persists.

**Comment by AnnMarieW** [comment]
Here's the [app on PyCafe](https://py.cafe/snippet/dash/v1#c=H4sIAH0jEWcAA71WbW_bNhD-KwL7JQNswbLs-AXQhzRtsWEZMGxD9yEqBFqiLdYUqZFUEiXwf99zkpwua9wUaFEbsEXePffcHXl3emC5KQRbs1TLqjbWBwV3ZVZx7aUWWW6wqYX2LuAuKKo81Vtrqk4pGABv8DwKsg5nhS6EFXYUlL5SqX66G2ZOeKx47rMbYZ00-ixl0TKchpOU_ZTqVPO6DpLO5Jm488JqrjLnWyVcKYR3CVwI-3V4cXXVQR59BJDEr7m9LLn1Z6kO8CmTeDIZ9c8F9zy57p_p85CyompStg66hyhlIzy93W5lLoXO28DlxgqSR7AB0Z-e-8b1gKOa71G5Ucb2klfx9PJNPE3ZYeB9hgvSU1yL5f-pftFfIHv37mI-Qf6-QBb_wMBmP5BrfpprufreSTw_TbaafxPZh-H_VvoSt_c9V4244huhkr9sIwahsWSMexRNkjKUj5c5VzDei3dWFhd30kHWPm5uuP3dmtolCMXyQvbezY-8VA6_ihaQLs5h1wkwueQaGM2rLr7noj4cvYYf-ys0C5jRqMPOzrGWQ8Vb0xwr87e-q8ClG4mGMBToY_0OMLkNsoyYsyxIEnBnaEdSZxk86RFk2Db6rBCbZtflCEA2Ylb800grKupXaGnUe1JNv-Ohn40_9bMkmYTRLDwHzLc1dUBSxArG30txy9ZbrpwYMVFI_1bzjYKOp-NgdetLo4GoW1MgkPHNJJyehxHAfbhs_UAHRP2Nrafwyxj_h4HJhyOXxWrE8lKqAs2Rra8fJZ5v0CQhvJWFL9k6mk9GrJL6734Z96ufhdyV4KGlLADbSiVewyoO79LgmiBYe4KBVMebXhcqNSe7DOd5GH3uxQkXP-HoLOoWV_l58X-PJPR3_inNV6Th5dCHUF4K-xjx83GWg9VoMf8aTkwmbHP1EulRj1jpexh16cftvP6A22LyPS3JChIE_VdBiVuIEl0tZiKOuFjwmVgtJ8uJ2E5jge1ptImiONUbJfVe2CSJQsxPTEFqCFuZJNPJdIaBSluYgohurI2tuJL3pB2HcSdSKNokWYZRuOhLBMAQkzgaCoZq_Em1YERjSPdCmu0nhadLbVBAzpVIknmP2Sru4EmMFaKShea0gFP924WSm3ElPO8mN_wFCiLvCq53wpqmI6fXB_1R6o98SuCILFXc7pva8S2oEFk4T7UWzo-5a3UuDeXtnGC1Ml615A7ShuiPNV16X5PjwKaabjHAHVkcEcwKb1upd2QnDmepRqKb2hujoHS-gp-AOXlH8qgjwgnzXHpQrfrIcUVgYEyvOdA0GkB40FlvrELgcR8bDN0Ku78X6HVdnsB2L2t4h6OEg-BxeNVih38B81MyQcwJAAA) - I don't see the issues

**Comment by namakshenas** [comment]
Ok. The culprit was this line:

`xAxisProps={"padding": {"left": 5, "right": 5}},`

Removed and now this issue is also fixed.

Thank you!

**Comment by AnnMarieW** [comment]
Great!  
In the future, could you please start by asking questions on Discord (or the Dash forum if it's just a dmc or Dash question) and then opening issues here if you find a bug ?

**Comment by namakshenas** [comment]
> Great! In the future, could you please start by asking questions on Discord (or the Dash forum if it's just a dmc or Dash question) and then opening issues here if you find a bug ?

I'll keep it in my mind. Also, appreciate your great help!
