### ISSUE TITLE
withBarValueLabel not displaying in correct positions

### ISSUE THREAD

**Issue by namakshenas** [snehilvj/dash-mantine-components#363]
Hi,

I'm trying to use the `withBarValueLabel` property of BarChart. The value labels are not placed correctly. Here is the snapshot of the issue:

<img width="1375" alt="Screenshot 2024-10-17 at 13 13 45" src="https://github.com/user-attachments/assets/99380eb1-392a-4e75-b18f-f5696b0df4f1">

Here is the code for reproducing the above chart (and of course issue):

```
data = [
    {"dmu": "dmu1", "Efficiency score": 100,
        "Status": "Efficient", "color": "#32CD32"},
    {"dmu": "dmu2", "Efficiency score": 78,
        "Status": "InEfficient", "color": "#FFA500"},
    {"dmu": "dmu3", "Efficiency score": 100,
        "Status": "Efficient", "color": "#32CD32"},
    {"dmu": "dmu4", "Efficiency score": 100,
        "Status": "Efficient", "color": "#32CD32"},
    {"dmu": "dmu5", "Efficiency score": 89,
        "Status": "InEfficient", "color": "#FFA500"},
    {"dmu": "dmu6", "Efficiency score": 95,
        "Status": "InEfficient", "color": "#FFA500"},
]

html.Div(
    [
        dmc.Divider(label="Efficiency scores", labelPosition="left", mt=10, mb=5),
        dmc.BarChart(
            h=400,
            dataKey="dmu",
            data=data,
            xAxisProps={"padding": {"left": 5, "right": 5}},
            yAxisProps={"padding": {"top": 30, "buttom": 30}},
            gridAxis=None,
            tickLine=None,
            withLegend=True,
            withBarValueLabel=True,
            legendProps={"payload":
                            [
                             {"dataKey": "Efficient", "type": "square",
                                 "id": "ID01", "color": "#32CD32"},
                             {"dataKey": "InEfficient", "type": "square",
                                 "id": "ID02", "color": "#FFA500"},
                         ],
                            "verticalAlign": "bottom", 
                            "height": 50
                         },
            unit="%",
            barProps={
                "radius": 5,
                "isAnimationActive": True,
            },
            orientation="vertical",
            series=[
                {"name": "Efficiency score"},
            ],
        ),
    ],
)
```

**Comment by AnnMarieW** [comment]
Hi @namakshenas 

If you create the same chart in Mantine, do you get the same results?  Since dmc is just a wrapper around Mantine, need to figure out if this is a dmc bug or not.

**Comment by namakshenas** [comment]
Hi @AnnMarieW,

Here is the working example in @mantine/charts:

```
<BarChart
          h={300}
          data={[
            { dmu: 'dmu1', 'Efficiency score': 100, Status: 'Efficient', color: '#32CD32' },
            { dmu: 'dmu2', 'Efficiency score': 78, Status: 'InEfficient', color: '#FFA500' },
            { dmu: 'dmu3', 'Efficiency score': 100, Status: 'Efficient', color: '#32CD32' },
            { dmu: 'dmu4', 'Efficiency score': 100, Status: 'Efficient', color: '#32CD32' },
            { dmu: 'dmu5', 'Efficiency score': 89, Status: 'InEfficient', color: '#FFA500' },
            { dmu: 'dmu6', 'Efficiency score': 95, Status: 'InEfficient', color: '#FFA500' },
          ]}
          withBarValueLabel
          orientation="vertical"
          gridAxis="y"
          barProps={{ radius: 5 }}
          dataKey="dmu"
          series={[{ name: 'Efficiency score' }]}
          tickLine="none"
/>
```

And the snapshot:

<img width="1151" alt="Screenshot 2024-10-17 at 16 08 52" src="https://github.com/user-attachments/assets/c7284022-2114-402f-8b85-a9e5c1acc0fa">


Unfortunately, withBarValueLabel is not displaying their correct positions using `@mantine/charts`

**Comment by namakshenas** [comment]
The issue posed [here](https://github.com/mantinedev/mantine/issues/6991).

**Comment by AnnMarieW** [comment]
OK, I'll close this now - but feel free to update this with any new information in the future.

**Comment by namakshenas** [comment]
The issue is fixed and waiting for approval: [PR #7011](https://github.com/mantinedev/mantine/pull/7011)

**Comment by namakshenas** [comment]
Issue fixed [#7042](https://github.com/mantinedev/mantine/pull/7042)

**Comment by namakshenas** [comment]
> OK, I'll close this now - but feel free to update this with any new information in the future.

Hi @AnnMarieW 

Issue fixed [#7042](https://github.com/mantinedev/mantine/pull/7042)

**Comment by AnnMarieW** [comment]
Hi @namakshenas - do you have an example of how to use this?  Does it require passing a function as prop?

**Comment by namakshenas** [comment]
> Hi @namakshenas - do you have an example of how to use this? Does it require passing a function as prop?

No need. That was an issue caused by the [mantine](https://github.com/mantinedev/mantine).

In the next release of dmc, you should change the mantine version to the latest release. Thanks!

dmc.BarChart(
           withBarValueLabel=True,
            ...
        ),

**Comment by AnnMarieW** [comment]
Nice!  Thanks :-)

**Comment by AnnMarieW** [comment]
This should be fixed in the next dmc release when we upgrade to 7.14.0 :tada:
