### ISSUE TITLE
Notifications stopped working with dmc>=0.14.5

### ISSUE THREAD

**Issue by Haladesta** [snehilvj/dash-mantine-components#382]
I have a larger app that uses Notifications and when I upgraded from 0.14.4 to 0.14.5 I noticed that notifcations suddenly stpped appearing without any errors. 
Looking into the DOM, I found that suddenly there were 5 nodes all with the same class "m_b37d9ac7 mantine-Notifications-root" and when rolling back, it was only one.
I can see the notification appearing on one of the notification roots, but it doesn't show up.
I tried reproducing it in a small app, and I can again see the 5 instances, but somehow the notifications are visible.

![image](https://github.com/user-attachments/assets/f28f031a-57f1-4e87-92d1-d9655351b506)

Any help would be appreciated, since I'm not sure if this is intended behaviour.

**Comment by AnnMarieW** [comment]
Hi @Haladesta 

How area you adding the notifications stylesheet?

**Comment by AnnMarieW** [comment]
ok, so it's not the stylesheets. :thinking: 

I'm afraid I can't help without a reproducible example.

**Comment by Haladesta** [comment]
Ah thanks you, yes that led me to the problem. I still had an older version added.
