### ISSUE TITLE
maxDropdownHeight height for Multiselect not working

### ISSUE THREAD

**Issue by monuyadav016** [snehilvj/dash-mantine-components#39]
If maxDropdownHeight property does what it says then it's clearly not functioning.

![image](https://user-images.githubusercontent.com/21173250/153750223-decda38e-5da5-42a0-b15f-bba5ac2c5411.png)

I would like the multiselect to occupy no more than the first line of values. I would be requiring few dropdowns that have hundreds of items to select and filter from. Is there any way I can fix the height of the dropdown to a specified number of pixels?

I wonder if someone has checked the kind of dropdown google datastudio provides.
![image](https://user-images.githubusercontent.com/21173250/153750420-33cb2b93-5b6e-4002-ad4f-b32a54ac028f.png)
It occupies no more than a single line.

**Comment by snehilvj** [comment]
maxDropdownHeight sets the maximum height of the dropdown which is working fine. What you are looking for is not supported by MultiSelect component. But you should be able to get this behaviour using Checkbox Inputs with a Popover. Popover not available in dmc right now, I'll try to add it but meanwhile have a look at using Popover from dbc.

https://dash-bootstrap-components.opensource.faculty.ai/docs/components/popover/

**Comment by monuyadav016** [comment]
Thank you @snehilvj . I thought it would restrict the height of the MultiSelect component. It occupies a lot of space when multiple things are selected and disturbs the entire layout.
