### ISSUE TITLE
LoadingOverlay component

### ISSUE THREAD

**Issue by Roh-codeur** [snehilvj/dash-mantine-components#40]
Hi

A newbie to web development here. for newbies like me, this package is a god-send. I can't thank you enough for putting this together and doing such an amazing job at docs (which I am using to learn) as well! 

Do you think we could have the below from mantine as well please?

https://mantine.dev/core/loading-overlay/

I am not very good at web development, but, if there is a straight forward way to migrate, I am happy to help and send a PR. if you do this one, I will make a note of steps and follow it through to migrate others - how does that sound?

thanks
Roh

**Comment by snehilvj** [comment]
Hi @Roh-codeur thanks for your kind words. I’m already working on LoadingOverlay component for the 0.5.0 release. May I ask how you plan to use this component because dmc.LoadingOverlay doesn’t quite work like doc.Loading. I can make it work like that but I’d like to know your use case.

**Comment by Roh-codeur** [comment]
Hi, I am planning to use this component as shown in the below link:

https://dash.plotly.com/dash-core-components/loading

I load some data from a file, show user a form, do some calculations etc. I, now, want to show the results in datatable, chart some results etc. the data table, graphs would be wrapped inside a Loading component, similar to the link shown above. 

You are right, the component doesn't seem to work like the Loading component. I think the more similar component is the Skeleton component.  I can see you have already migrated this. I am not sure how to show a Spinning Loader with this though. Am I on the right track?

https://mantine.dev/core/skeleton/

**Comment by snehilvj** [comment]
You are right, Skeleton works like you intend it to except you can’t show a spinning loader. I’ll try to make LoadingOverlay work like dcc.Loading.

**Comment by Roh-codeur** [comment]
Thanks buddy! I like how loading overlay can be used to overlay a form and the results at the same window. I would like to achieve the same effect if possible

Thanks!

**Comment by snehilvj** [comment]
I have implemented the component similar to dcc.Loading. Here's how it will look:

https://user-images.githubusercontent.com/91216500/154955058-074099eb-cc68-4659-9005-3e3f420a615b.mov

**Comment by Roh-codeur** [comment]
You bhai, are a Star! Thanks a lot. Does this also work the same way on forms? As in:
1. User fills a form
2. Presses submit to generate report of tables and charts

Overlay shows on both form and the data table, hiding when data table and graph have finished rendering?

**Comment by snehilvj** [comment]
This component is released in version 0.5.0. Have a look [here](https://dash-mantine-components.herokuapp.com/components/loading-overlay).

**Comment by Roh-codeur** [comment]
thanks buddy! this is awesome, you are a Star! I will give it a shot now.
