### ISSUE TITLE
[bug] Popover does not close on outside click despite `closeOnClickOutside=True`

### ISSUE THREAD

**Issue by magicmq** [snehilvj/dash-mantine-components#420]
Popovers open as expected when clicking on the target (Button, ActionIcon, etc.); however, the popover does not close when clicking outside of it. According to the docs, the `closeOnClickOutside` argument is `True` by default, so I expect the popover to close on outside click by default. Nevertheless, I have tried explicitly setting `closeOnClickOutside=True`, but the issue persists. I have also tried setting `trapFocus=False` for the popover (even though the docs states `trapFocus` is `False` by default).

[The example on the docs](https://www.dash-mantine-components.com/components/popover) appears to exhibit the same behavior.

**Reproducible example:**
```py
from dash import Dash, html, _dash_renderer
import dash_mantine_components as dmc

_dash_renderer._set_react_version("18.2.0")

app = Dash(__name__, external_stylesheets=dmc.styles.ALL)

app.layout = dmc.MantineProvider(dmc.Box(
    [
        dmc.Popover(
            [
                dmc.PopoverTarget(
                    dmc.Button(
                        'Toggle Popover'
                    )
                ),
                dmc.PopoverDropdown(
                    dmc.Stack([
                        dmc.Title('A Popover', size='lg', order=4, c='black'),
                        dmc.Text('When clicking outside of the popover dropdown, the popover should close, but it does not. Instead, the user must click on the Popover target again to close the popover.'),
                    ], gap='xs')
                )
            ],
            width=400,
            closeOnClickOutside=True # According to the docs, this is True by default, but specifying explicitly just in case
            trapFocus=False, # According to the docs, this is False by default, but specifying explicitly just in case
        )
    ],
    m=10
))

app.run_server(debug=True)
```
**Steps to reproduce:**
1. Run the above script with dash and dash-mantine-components installed.
2. Navigate to http://localhost:8050.
3. Click the 'Toggle Popover' button.
4. Click anywhere onscreen outside of the popover.
5. Notice that the popover does not close.

**Comment by AnnMarieW** [comment]
Hi @magicmq 
Thanks for reporting!  I found a discussion about how to fix this on the Mantine Discord:  https://discord.com/channels/854810300876062770/1271832774877122663

**Comment by magicmq** [comment]
> Hi @magicmq Thanks for reporting! I found a discussion about how to fix this on the Mantine Discord: https://discord.com/channels/854810300876062770/1271832774877122663

@AnnMarieW, thank you! Unfortunately that Discord URL doesn't take me anywhere, and I tried to search for the discussion myself, but no luck :(

**Comment by AnnMarieW** [comment]
This was from the Mantine discord, rather than the dmc discord.  Are you on that server as well?  To find it, go to the support section and search for "controlled Popover".  

This will have to be fixed in component rather than the Dash app.

**Comment by magicmq** [comment]
Ahh, completely missed that in your reply, my apologies. Thank you again!

**Comment by AnnMarieW** [comment]
more clues for a fix:  https://github.com/mantinedev/mantine/issues/7019
