### ISSUE TITLE
[Feature Request] Add support for Select / MultiSelect label icons

### ISSUE THREAD

**Issue by IstvanM** [snehilvj/dash-mantine-components#437]
Hi `dcc.dropdown` has support for the icons in the. I believe this would be a great addition to the dmc Select and MultiSelect components as well.

Mantine supports this with the: [renderOptions](https://mantine.dev/core/multi-select/#renderoption) feature

**Comment by AnnMarieW** [comment]
Hi @IstvanM 

This `renderOption` prop requires a function and that is not currently supported.  It's on the roadmap though, so please chime in on issue #356 

I'll close this as a duplicate for now.  Thanks for your request
