### ISSUE TITLE
BubbleChart doesn't follow the forceColorScheme color change

### ISSUE THREAD

**Issue by pip-install-python** [snehilvj/dash-mantine-components#438]
<img width="944" alt="Screenshot 2024-12-01 at 1 03 36 AM" src="https://github.com/user-attachments/assets/d7d2172f-d2f2-40e1-a2c7-e176e887506a">

Working through a project using the dmc. BubbleChart and noticed a bug with forceColorScheme="dark" when forceColorScheme="light" BubbleChart ledger looks correct however if forceColorScheme="dark" the ledger doesn't turn white and your left with:
<img width="198" alt="Screenshot 2024-12-01 at 12 57 21 AM" src="https://github.com/user-attachments/assets/31c9f904-24fe-4dd7-9992-d971438cb23e">
The Text is their just really impossible to read the ledger on dark theme.

<img width="955" alt="Screenshot 2024-12-01 at 1 07 06 AM" src="https://github.com/user-attachments/assets/912457e7-3919-405d-8b9e-25ba1c5543c0">

**Comment by AnnMarieW** [comment]
@pip-install-python 
Can you please include a reproducible example?  This feature works fine in the docs.  Looks like you might have something interfering with the figure's CSS.
