### ISSUE TITLE
dmc.Slider does not respect restrictToMarks for keyboard Input

### ISSUE THREAD

**Issue by joAschauer** [snehilvj/dash-mantine-components#439]
Hey there, 

the dmc.Slider component has the option `restrictToMarks` which ensures that users can only select values matching the specific marks defined. I just noticed, that is it possible to select values other than the defined marks via keyboard even though `restrictToMarks=True`.

![Screenshot 2024-12-02 155155](https://github.com/user-attachments/assets/14887a19-550e-4541-b144-85d927879346)

Here is a MWE:
```python
import dash_mantine_components as dmc
from dash import Dash, Input, Output, _dash_renderer

_dash_renderer._set_react_version("18.2.0")

app = Dash(external_stylesheets=dmc.styles.ALL)

component = dmc.Slider(
    id="slider",
    restrictToMarks=True,
    value=25,
    marks=[
        {"value": 25, "label": "25%"},
        {"value": 50, "label": "50%"},
        {"value": 75, "label": "75%"},
        {"value": 85, "label": "85%"},
        {"value": 95, "label": "95%"},
    ],
    m=30,
)

app.layout = dmc.MantineProvider(
    [
        component,
        dmc.Text(id="slider-output"),
    ]
)


@app.callback(Output("slider-output", "children"), Input("slider", "value"))
def update_value(value):
    return f"You have selected: {value}"


if __name__ == "__main__":
    app.run(debug=True)
```

**Comment by AnnMarieW** [comment]
Hi @joAschauer 

Thanks for reporting.  That was fixed upstream in the latest Mantine release  https://github.com/mantinedev/mantine/releases/tag/7.14.3

This will be available in the next dmc release 0.15.1 which should be available later this week.
