### ISSUE TITLE
LineChart drops column if there is one missing value

### ISSUE THREAD

**Issue by Wapaa** [snehilvj/dash-mantine-components#443]
Hello everyone,
I have data that looks like the data below. When I try to plot it  with dataKey='date' and series (FITC, CY5, DAPI, and TRITC). If there's a null value in any line, it drops it from the graph. How can I adjust this to just skip that data point?

`data = [{'DAPI': 42212.44284955681,
  'FITC': 39579.08263156841,
  'dataset_index': 0,
  'date': datetime.date(2024, 11, 29),
  'CY5': nan,
  'TRITC': nan},
 {'DAPI': 43525.87908987836,
  'FITC': 41935.75454605864,
  'dataset_index': 1,
  'date': datetime.date(2024, 11, 29),
  'CY5': 41124.016080595175,
  'TRITC': 42618.78987275943},
 {'DAPI': 45706.72574325567,
  'FITC': 42922.41592194716,
  'dataset_index': 2,
  'date': datetime.date(2024, 11, 29),
  'CY5': 45567.41051876721,
  'TRITC': 42027.75111531162},
 {'DAPI': 42409.59461449837,
  'FITC': 44240.63513784188,
  'dataset_index': 3,
  'date': datetime.date(2024, 11, 29),
  'CY5': 44792.27478468819,
  'TRITC': 45347.34554698756}]`

**Comment by AnnMarieW** [comment]
Working through this issue on the forum:  https://community.plotly.com/t/linechart-drops-column-if-there-is-one-missing-value/89171/
