### ISSUE TITLE
Not available in anaconda or conda-forge sources

### ISSUE THREAD

**Issue by ibby-dev** [snehilvj/dash-mantine-components#45]
Please could you add this to anaconda and/or conda-forge sources? Thank you.

**Comment by snehilvj** [comment]
Hi @ibby-dev thanks for reporting. I have initiated the process in https://github.com/conda-forge/staged-recipes/pull/18187

**Comment by snehilvj** [comment]
@ibby-dev can you check now if it is available?

**Comment by snehilvj** [comment]
Its part of conda-forge repo now.
