### ISSUE TITLE
[Feature Request] multi-step wizards

### ISSUE THREAD

**Issue by mohammadaffaneh** [snehilvj/dash-mantine-components#462]
**Problem:**  
Creating multi-step wizards with form validation and data operations (CRUD), requires a lot of repetitive Python code and custom callbacks. This makes it hard to reuse code and slows down development.  

**Propsal:**  
DMC already has powerful tools like `Stepper` for navigation, `TextInput`, `Button`, `Validation and notifications`, and many other for inputting and dispalying data. By combining these into a reusable **multi-step wizard** that includes:  
- Built-in validation (e.g., checking required fields before moving to the next step)  
- Easy data handling (like integrating with CRUD operations)  
- Modular components that developers can configure and reuse  

---

### Imagination of usage
Let’s say we want a registration wizard where users must complete required fields before moving to the next step.  

**Step 1: Create Steps**  
```python
step1 = WizardStep(
    label="User Info",
    components=[
        dmc.Text("Enter your name:", weight=500),
        dmc.TextInput(id="username-input", placeholder="Your Name")
    ]
)
step2 = WizardStep(
    label="Contact Details",
    components=[
        dmc.Text("Enter your email:", weight=500),
        dmc.TextInput(id="email-input", placeholder="Your Email", type="email")
    ]
)
```

**Step 2: Set Required Fields**  
```python
required_components = [
    {"step": 0, "component": {"id": "username-input", "property": "value"}},
    {"step": 1, "component": {"id": "email-input", "property": "value"}}
]
```

**Step 3: Build the Wizard**  
```python
wizard = FormWizard(
    app=app,
    steps=[step1, step2],
    wizard_id="my-wizard",
    required_wizard_components=required_components
)
```

**Final Layout:**  
```python
app.layout = dmc.Container(
    [
        dmc.Title("Registration Wizard", order=2),
        wizard.component
    ],
    style={"padding": "2rem"}
)

if __name__ == "__main__":
    app.run_server(debug=True)
```

In which `WizardStep` defines each individual step with its components, while `FormWizard` manages the entire multi-step process, including navigation, validation, and layout integration.

More ideas; `tryformly.com`

**Comment by AnnMarieW** [comment]
Hi @mohammadaffaneh 

This would be a great component, but it would be better as a separate project.  The Dash Mantine Components aims to mirror the upstream Mantine library.

Check out this great project for making forms that uses DMC:   https://github.com/RenaudLN/dash-pydantic-form
You could likely use this along with the Stepper to create your forms Wizard

**Comment by mohammadaffaneh** [comment]
Thanks for the reference, agree on your point.

Appreciate the support!
