### ISSUE TITLE
DateRangePicker Singe Date Selection Issues

### ISSUE THREAD

**Issue by bigmike36c** [snehilvj/dash-mantine-components#47]
Hello,

Really appreciate your work on this awesome project! 

I'm having issues selecting a single date with the daterangepicker. The first issue is with the UI as shown below. When trying to select a single date the first time, the selection simply disappears. However, the second time I select a single date, it stays.

https://user-images.githubusercontent.com/81941044/155823051-aebb582d-e2f4-44bd-a8d9-7200f4520c81.mov

The second issue is triggering a callback with a single date selection. Can this be done? I was hoping the callback value would be something along the lines of ["selected_start_date", maxDate], but a single selection does not appear to trigger the callback.

Thanks in advance for any help.

**Comment by snehilvj** [comment]
Hi @bigmike36c, Thanks for reporting this issue. I agree with your comment about the behaviour and I have corrected that (will be released in 0.6.0).
Regarding your second issue, can you please briefly explain your process? How will you use it if single date selection were to trigger a callback.

**Comment by bigmike36c** [comment]
Thanks for correcting this so quickly!

In my mind, if a user only selects a single date, then the user expects the date range to extend from the start date to the maximum date available.

The code snippet below is essentially how I've been handling this with the default dcc.DatePickerRange. If the callback is triggered with only one date selected (either start or end), the other date is simply set to an empty string in the callback. I then convert the empty string to the minimum or maximum date in the dataframe. 
```
start_date = start_date or df["datetime"].min()
end_date = end_date or df["datetime"].max()
```
Since the dmc.DateRangePicker only lets you select the start date on its own, I think it would make the most sense for the callback to receive ["selected_start_date", maxDate]. If the maxDate parameter was not set, it could be replaced with an empty string or None.

**Comment by snehilvj** [comment]
Okay got it.
I can think about partial callback where in you at least get one date which is selected (keeping in mind backwards compatibility).
But I don't think we can do
> callback to receive ["selected_start_date", maxDate].
It makes the date range picker less intuitive as to what's in the value is not what's displayed, etc.

**Comment by bigmike36c** [comment]
Makes sense to me. Could the callback just trigger with `"selected_date"` as a string instead of a list? This would make it easy to handle both single date and range selections in the callback logic with the `isinstance()` function.

**Comment by snehilvj** [comment]
Ability to select single date won't be supported in dmc.DateRangePicker, for such purposes please use two date pickers.
