### ISSUE TITLE
Passing custom control to menu?

### ISSUE THREAD

**Issue by john-wallace-dev** [snehilvj/dash-mantine-components#62]
Is there a way to pass a custom control to Menu? Currently I get the '...' ActionItem, but would really like to use my own button as described in https://mantine.dev/core/menu/.

Great job, btw. Very helpful!

**Comment by john-wallace-dev** [comment]
For others having this problem, I gave my menu a class_name of 'example-menu' and used a css trick to hide the existing ... and display my svg. Something like this:

`
.example-menu button {
    width: 24px;
    color: transparent;  /* hide the ... */
}

.example-menu button:before {
    display: block;
    content: '';
    background: url('name-of-file-in-my-assets-folder.svg') no-repeat;
    background-size: 20px 20px;
    height: 19px;
    width: 24px;
} 
`

**Comment by snehilvj** [comment]
Hi @john-wallace-dev The reason I am not able to do it as a part of dmc library itself is because of the way its handled in the Mantine react library. I am still working on it. Meanwhile, users can use your suggestion.

**Comment by snehilvj** [comment]
This is improved in Mantine v5 (as seen in some of the alpha releases). Once Mantine v5 is released, dmc Menu will be upgraded too.
