### ISSUE TITLE
Tabs with empty children throws a javascript exception

### ISSUE THREAD

**Issue by john-wallace-dev** [snehilvj/dash-mantine-components#64]
When I set the children to a Tabs object to either None or [], I get a javascript exception:

"undefined is not an object (evaluating 'S[j].props')"

That happens when I write something line:

`
dmc.Tabs(
    id='some-id',
    children=[]
)
`

or 

`
dmc.Tabs(
    id='some-id',
    children=None
)
`

For others running into this problem, my workaround when I shouldn't have any tabs is to create a Tab() and assign it a class_name where the style is 'display: none'.

So in my python code: 

`
dmc.Tabs(
    id='some-id',
    children=dmc.Tab(label='', class_name='tab-hidden'))  # Must have at least 1 tab or throws error
`

And in my css file:

`
.tab-hidden {
    display: none;
}
`

**Comment by snehilvj** [comment]
Fixed in the latest master.
