### ISSUE TITLE
Publish to unpkg CDN

### ISSUE THREAD

**Issue by theodcr** [snehilvj/dash-mantine-components#65]
Hi! Thanks for this project that brings great components to the Dash ecosystem!

I would like to use dash-mantine-components for a Dash project in production where I prefer to use the unpkg CDN for delivering the JS sources of Dash components. However I noticed that the sources for dash-mantine-components are inexistent on unpkg.

Do you plan to publish your components to NPM to make them available on unpkg?
Thanks!

**Comment by snehilvj** [comment]
Hi @theodcr 
I'll publish the components to NPM as soon as I am able to. Thanks for bringing this to my attention.

**Comment by Juasmis** [comment]
Any updates on this?

**Comment by snehilvj** [comment]
Not yet, I had to take up Javascript to Typescript migration. So the next release will be available through NPM as well.

**Comment by snehilvj** [comment]
I have setup the repo to publish to npm, in fact I published the latest 0.11.0a0 release to npm. The issue was that on npm its listed as version 0.11.0-a0. So you can't really use it, but now that things are setup, the 0.11.0 release will be published on npm and you can use `serve_locally=False`.
