### ISSUE TITLE
DateRangePicker - Selecting same dates subsequently without clearing is not working

### ISSUE THREAD

**Issue by pavolpluta** [snehilvj/dash-mantine-components#66]
When I want to select the same dates subsequently it's not working properly. The input field remains blank. It works when I click on the clear X symbol, but not when I select it. 

Callback for blank value field is sadly also not triggered. Again, when I hit 'X' button, callback is triggered.

I'm including the video demonstration using docs daterangepicker as an example:

https://user-images.githubusercontent.com/31762827/164442467-14881a24-bf1b-4bd7-858a-2a397924c2c1.mov

In the first part of the video you see broken behavior (without 'X' button), callback is not triggered. In the second part (with 'X' button), everything works as expected, callback in Dash is triggered.

The same unexpected behavior is also applied for  `allowSingleDateInRange=True`.

Otherwise, I really appreciate all of the effort you put into this project. It's great.

Thanks!

**Comment by snehilvj** [comment]
The issue still persists (even while using Mantine v5). I'll pick this up just before the release, but any proposal from the community is welcome.

**Comment by snehilvj** [comment]
This is fixed, will be available with the next release.
