### ISSUE TITLE
onLabel and offLabel not working in switch component (Inner Labels)

### ISSUE THREAD

**Issue by jinopg** [snehilvj/dash-mantine-components#74]
Inner Labels

import dash_mantine_components as dmc

dmc.Switch(
    label="I agree to sell my privacy",
    onLabel="ON",
    offLabel="OFF"
)

Also the bullet is not positioned at center of slot, its is top aligned

**Comment by snehilvj** [comment]
Hi @jinopg 
Can you provide the version of dmc you are using along with any screenshots? I can see it working fine on my machine as well as in the documentation.

**Comment by jinopg** [comment]
![dash mantine](https://user-images.githubusercontent.com/60698030/170704176-4203c2f9-fcbc-4a86-a3ba-6dd5be076514.png)
 dash_mantine Version is 0.8.0

**Comment by snehilvj** [comment]
Do you see this behaviour on https://www.dash-mantine-components.com/components/switch? If not then you might have a CSS file which is causing this issue or might be a browser issue. Which browser are you using btw?

**Comment by jinopg** [comment]
I used the  same link for mantine switch.  I am not using any css for mantine. Parallelly i am using bootstrap components fot that I am using css files. But I tried a switch seperately in a tab and it didn't work properly. I am using edge browser. I think I tried with other browser also. I will check again and confirm that

**Comment by snehilvj** [comment]
Can you please confirm if you see this issue in the documentation website or not?

**Comment by jinopg** [comment]
In documentation it works perfectly well, I tried with all browsers, everywhere it shows same output.
![switch dmc](https://user-images.githubusercontent.com/60698030/172174200-679f375e-bb10-4852-963b-c84e98dd5f24.PNG)

**Comment by snehilvj** [comment]
If its working fine in docs, then it's because of some conflicting CSS. You can check in dev tools window of the browser for that conflicting CSS source. Otherwise you can share your repository and I'll have a look.

**Comment by jinopg** [comment]
yes man you are right, its a conflicting CSS file from assets. when I removed it is working well. but my question how we could avoid this, I want to run a DASH application on a local machine, where I am restricted to use internet. If I keep dash bootstrap CSS files on assets will it make any issues??

**Comment by snehilvj** [comment]
I have not heard of any compatibility issues between dash bootstrap and dash mantine components so far.
