### ISSUE TITLE
dayStyle property in datePicker

### ISSUE THREAD

**Issue by Juasmis** [snehilvj/dash-mantine-components#76]
Hi! I have a database with some information over the years. The user using the datePicker can select a day and if there is data then it can continue but if not an alert is generated. I would like it to make it easier for the user to select a date by highlighting the days with data with a green background (so when creating the component I would pass in a list of days and modify its appearance). I have seen this is possible in the original library [Styles based on date](https://mantine.dev/dates/calendar/) by using the property dayStyle but I am not sure if this is possible in the python version since it does not appear in the documentation. 

![image](https://user-images.githubusercontent.com/48693399/171448922-e6072f4b-d688-49ec-92fb-94af6e2ac5b1.png)

**Comment by snehilvj** [comment]
This is taken care of in the coming release.
