### ISSUE TITLE
switch progress bar color depending on the theme

### ISSUE THREAD

**Issue by Don-Yin** [snehilvj/dash-mantine-components#78]
Hi there, 

Again, this is not really issue. Because you don't have a discussion section, I'll post my question here; hope that's okay?

My question: is there a way to change the colours in the progress bar after changing the theme, so that the colour looks more consistent with each of the dark/light background?

Allow me to explain:

In light mode, the progress bars now look like this:

<img width="1013" alt="Screenshot 2022-06-15 at 02 08 26" src="https://user-images.githubusercontent.com/65135356/173715037-60f15659-47d7-4890-82be-75aaee6400f8.png">

In the dark mode:

<img width="1025" alt="Screenshot 2022-06-15 at 02 08 36" src="https://user-images.githubusercontent.com/65135356/173715060-1bfc194c-40f4-4f6d-b944-ad792a9cff15.png">

Because of the dark background, it is far too gleaming.

The obvious solution is to use a callback to switch colours on the fly with a theme switch. As an example:

```python
@callback(
    Output(component_id="progress_bar", component_property="sections"),
    Input(component_id="theme_switch", component_property="n_clicks"),
)
def on_switch():
    """blablabla"""
    return ["""__some sections with new colors___"""]
```

 
The problem with this method is that none of the supported colours are appropriate for the dark mode (apart from dark and gray). I am thinking of something like a "darker indigo":
["dark", "gray", "red", "pink", "grape", "violet", "indigo", "blue", "cyan", "teal", "green", "lime", "yellow", "orange"](https://www.dash-mantine-components.com/components/progress)

Is it possible to make the progress bar colour look more "darky" in dark themes? Perhaps by adjusting the transparency? Is this currently an option?

Great work!
Don

**Comment by snehilvj** [comment]
Hi @Don-Yin 
Supplying hex values for colors might be possible once Mantine v5 is released but until then you have to use the theme colors in DMC. However these theme colors can be modified as per your requirement. Just wrap your app with MantineProvider and define the new theme color.

```python
app.layout = dmc.MantineProvider(
    theme={
        "colors": {
            # add your color
            "my-color": [
                "#E6E7EE",
                "#CBCDDE",
                "#B0B4D2",
                "#949ACB",
                "#777FC9",
                "#5662CC",
                "#3142D7",
                "#3744B7",
                "#3D4699",
                "#3F4681",
                "#3F446F",
                "#3D405F",
                "#3A3C53",
            ]
        }
    },
    children=[...],
)
```
How you generate these colors, you ask? Have a look here: https://omatsuri.app/color-shades-generator. I hope it helps.

**Comment by Don-Yin** [comment]
Hi @snehilvj ,

Thanks for your reply! Please correct me if I'm wrong; my next question is how you would apply those colours to individual progress bars. After adding these new colours to the theme provider, I discovered that they do not appear in the app. I attempted the following, but it did not appear to work:
```python
# ----apply themes----
app.layout = dmc.MantineProvider(  # apply themes to the whole app
    id="mantine-provider",
    theme={
        "colorScheme": "light",
        "fontFamily": "'Inter', sans-serif",
        "primaryColor": "indigo",
        "colors": {
            # add your color
            "my-color": [
                "#E6E7EE",
                "#CBCDDE",
                "#B0B4D2",
                "#949ACB",
                "#777FC9",
                "#5662CC",
                "#3142D7",
                "#3744B7",
                "#3D4699",
                "#3F4681",
                "#3F446F",
                "#3D405F",
                "#3A3C53",
            ]
        },
    },
    withGlobalStyles=True,
    withNormalizeCSS=True,
    children=layout,
)
```
+
```python
progress_bar = dmc.Progress(  # one for progress, one for distribution of nodes
    size="xl",
    radius=0,
    sections=[
        {"value": 30, "color": "#E6E7EE", "label": "Documents"},
        {"value": 30, "color": "#E6E7EE", "label": "Apps"},
        {"value": 25, "color": "#E6E7EE", "label": "Other"},
    ],
)
```

Maybe I am doing something wrong?

Cheers,
Don

**Comment by Don-Yin** [comment]
Thanks for your reply! 

Why does the size have to be 10? I'm just curious. Does each of these elements serve a distinct function?

Plus, it seems like it only works when we directly wrap around the theme provider on the progress bar itself:

```python
app.layout = dmc.MantineProvider(
    withGlobalStyles=True,
    withNormalizeCSS=True,
    theme={
        "colorScheme": "light",
        "colors": {
            # replace yellow
            "yellow": [
                "#C3C6A0",
                "#B3B780",
                "#A6AC63",
                "#979D4E",
                "#868C41",
                "#777D35",
                "#6A702B",
                "#585D27",
                "#494D23",
            ]
        },
    },
    children=[
        dmc.Progress(  # one for progress, one for distribution of nodes
            size="xl",
            radius=0,
            sections=[
                {"value": 30, "color": "yellow", "label": "Documents"},
            ],
        )
    ],
)
```

It stops working if we put the progress in a div:

```python
app.layout = dmc.MantineProvider(
    withGlobalStyles=True,
    withNormalizeCSS=True,
    theme={
        "colorScheme": "light",
        "colors": {
            # replace yellow
            "yellow": [
                "#C3C6A0",
                "#B3B780",
                "#A6AC63",
                "#979D4E",
                "#868C41",
                "#777D35",
                "#6A702B",
                "#585D27",
                "#494D23",
            ]
        },
    },
    children=[html.Div(
        dmc.Progress(  # one for progress, one for distribution of nodes
            size="xl",
            radius=0,
            sections=[
                {"value": 30, "color": "yellow", "label": "Documents"},
            ],
        )
)
    ],
)
```

Is this by design? Is there a way around this? This is totally fine but seemingly a bit strange this way.

Again, thank you very much for your response.
Don
