### ISSUE TITLE
How to implement Dash bootstrap theme  to dash mantine components

### ISSUE THREAD

**Issue by jinopg** [snehilvj/dash-mantine-components#79]
I had integrated mantine components like buttons, text input, accordion etc to my bootstrap based Dash APP. **while selecting the DARK themes all component labels and text is unreadable**. Is there a way to resolve this. is there an simple way to resolve this at least.
![mantine theme issue](https://user-images.githubusercontent.com/60698030/173783308-f353db80-673f-47e8-bde6-9d15dc0ef3d4.jpg)
 the label colours and text colours.

**Comment by snehilvj** [comment]
Hi @jinopg 
DMC supports dark theme via its MantineProvider component. Have a look [here](https://www.dash-mantine-components.com/components/mantineprovider) for more information.
