### ISSUE TITLE
Does dmc.MultiSelect creatable argument allow the user to enter a custom option?

### ISSUE THREAD

**Issue by df-seagate** [snehilvj/dash-mantine-components#82]
First I would like to say that these components are great!

I have the following:
```
dmc.MultiSelect(
    label="My Dropdown",
    id="my-dropdown",
    value=[],
    data=[
        {"value": "parameter1", "label": "Parameter1"},
        {"value": "parameter2", "label": "Parameter2"},
        {"value": "attribute1", "label": "Attribute1"},
        {"value": "attribute2", "label": "Attribute2"},
    ],
    creatable=True,
)    
```

I was expecting that with the creatable=True argument I would be able to add a new option to the dropdown. 

Does MultiSelect component allow the user to add new options on the fly?

Thanks,
David

**Comment by snehilvj** [comment]
Source library Mantine has a bug related to `creatable` feature. Waiting for that to be addressed.

**Comment by snehilvj** [comment]
The bug has been fixed in Mantine and after upgrading its version in dmc, this feature is available in dmc too. It will be available in the next release.
