### ISSUE TITLE
Scrolling Capabilities within Drawer

### ISSUE THREAD

**Issue by kennethfungch** [snehilvj/dash-mantine-components#90]
I have recently come across this package and I must say I have been very impressed by it. I am still pretty new in this but I am not sure whether it is possible to do scrolling within a drawer if the content exceeds the screen size.

Thanks!

**Comment by nibu147** [comment]
Same request here, as no scrollbar appears with the following code:

```
    scrollable_drawer = dmc.Drawer(
        children=[
            dmc.ScrollArea(
                offsetScrollbars=True,
                type="hover",
                children=[
                    ... a lot of components
                ]
            )
        ],
        position='right',
        size=500,
        padding='md'
    )
```

**Comment by nibu147** [comment]
... it turned out that the solution, @kennethfungch , was quite easy in my case. I just had to add a `style={'height': 500}` property to the `dmc.ScrollArea` element.
