### ISSUE TITLE
Color index support

### ISSUE THREAD

**Issue by Lxstr** [snehilvj/dash-mantine-components#92]
Is there any supprt for color index as per [https://mantine.dev/theming/colors/#colors-index-reference](https://mantine.dev/theming/colors/#colors-index-reference)? 

The following code seems to have no effect
`dmc.Button(
                                        "Load data",
                                        variant="filled",
                                        color="green.9",
                                        fullWidth=True,
                                        n_clicks=0,
                                    ),`

Ps. great library many thanks!!

**Comment by snehilvj** [comment]
Hi, color indexing support has been added in dmc, it will be available to you in the next dmc release.

**Comment by Lxstr** [comment]
Amazing thanks
