### ISSUE TITLE
RadioGroup not rendering fully

### ISSUE THREAD

**Issue by yaszin** [snehilvj/dash-mantine-components#93]
I've been experiencing this issue lately with dmc.RadioGroup.

Using the docs example :
`        dmc.RadioGroup(
            id="radiogroup",
            data=[
                {"value": "react", "label": "React"},
                {"value": "ng", "label": "Angular"},
                {"value": "svelte", "label": "Svelte"},
                {"value": "vue", "label": "Vue"},
            ],
            value="react",
            label="Select your favorite framework/library",
            size="sm",
        )
`
This is how the output looks like:
![imagen](https://user-images.githubusercontent.com/67963519/190087816-c3f8f175-406a-4c8f-8c95-b3813aa0e8d5.png)

I can't still click on the options but it doesn't display the same way as in the demo.

**Comment by snehilvj** [comment]
I think some other CSS is causing this problem. Can you verify by removing other stuff step by step?
