### ISSUE TITLE
Additional arguments/properties for dmc.AccordionItem

### ISSUE THREAD

**Issue by alexshoe** [snehilvj/dash-mantine-components#94]
`dmc.AccordionItem` needs `style` and `class_name` properties to allow for component-level styling.

Would also be very useful for `dmc.AccordionItem` to have a boolean `opened` property that indicates whether or not the item is opened.

**Comment by snehilvj** [comment]
This has been taken care of in the master.
I don't think it's possible to have an `opened` property in Mantine, but I'm still exploring it.
