### ISSUE TITLE
Add `href` argument to Button

### ISSUE THREAD

**Issue by nlyle01** [snehilvj/dash-mantine-components#95]
It would be great if `dmc.Button()` had an `href` keyword argument, so that a button click can route to a URL

**Comment by mcpcpc** [comment]
> It would be great if `dmc.Button()` had an `href` keyword argument, so that a button click can route to a URL

Out of curiosity, why is this preferred over the standard `html.A()` wrap, which is the typical practice using the core dash components? i.e.


```
html.A(html.Button("Go Home!"), href="/")
```

**Comment by nlyle01** [comment]
Great point @mcpcpc, I overlooked that. I was comparing to the functionality of the [dash boostrap button](https://dash-bootstrap-components.opensource.faculty.ai/docs/components/button/).
