### ISSUE TITLE
conda-forge outdated

### ISSUE THREAD

**Issue by juanfcocontreras** [snehilvj/dash-mantine-components#96]
Latest version in conda-forge repository is 0.9:

```
# Name                       Version           Build  Channel
dash-mantine-components           0.6.0    pyhd8ed1ab_0  conda-forge
dash-mantine-components           0.7.0    pyhd8ed1ab_0  conda-forge
dash-mantine-components           0.8.0    pyhd8ed1ab_0  conda-forge
dash-mantine-components           0.9.0    pyhd8ed1ab_0  conda-forge
```

Could you please update it?

Thanks in advance!

**Comment by snehilvj** [comment]
Sorry I can't maintain this entry in conda forge, but some one from the community is welcome to take charge of it.

**Comment by ludaavics** [comment]
@snehilvj 

Isn't conda forge really low maintenance? Just need to merge the automatically generated PRs? I thought setting up the feedstock was by far the most work.

I'm happy to do it if  you can [add me as a member to the project](https://conda-forge.org/docs/maintainer/infrastructure.html#conda-forge-admin-please-add-user-username)
