### ISSUE TITLE
The value of the slider component is not updated

### ISSUE THREAD

**Issue by rmotadutra** [snehilvj/dash-mantine-components#97]
Trying to use a number input to update the slider component, but it's not possible.

Example of code:
```
app.layout = html.Div(
    [
        dmc.NumberInput(
            id="input_number",
            min=0,
            max=100
        ),
        dmc.Slider(
            id="slider",
            min=0,
            max=100
        )
    ],
)

@app.callback(
    Output("slider", "value"),
    Input("input_number", "value"),
)
def uptade_input_value(value):
    return value
```

![image](https://user-images.githubusercontent.com/47394022/196448723-c2c7af7e-a34d-4d9b-a4e8-285ba57e267b.png)

**Comment by snehilvj** [comment]
@rmotadutra I don't see this problem in the latest master, so it should go away in the next release.
